CREATE TABLE authors (
  id   BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name text    NOT NULL,
  bio  text
);

CREATE TABLE `items` (
  `id` int(11) NOT NULL DEFAULT 0,
  `minstatus` smallint(5) NOT NULL DEFAULT 0,
  `Name` varchar(64) NOT NULL DEFAULT '',
  `aagi` int(11) NOT NULL DEFAULT 0,
  `ac` int(11) NOT NULL DEFAULT 0,
  `accuracy` int(11) NOT NULL DEFAULT 0,
  `acha` int(11) NOT NULL DEFAULT 0,
  `adex` int(11) NOT NULL DEFAULT 0,
  `aint` int(11) NOT NULL DEFAULT 0,
  `artifactflag` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `asta` int(11) NOT NULL DEFAULT 0,
  `astr` int(11) NOT NULL DEFAULT 0,
  `attack` int(11) NOT NULL DEFAULT 0,
  `augrestrict` int(11) NOT NULL DEFAULT 0,
  `augslot1type` tinyint(3) NOT NULL DEFAULT 0,
  `augslot1visible` tinyint(3) NOT NULL DEFAULT 0,
  `augslot2type` tinyint(3) NOT NULL DEFAULT 0,
  `augslot2visible` tinyint(3) NOT NULL DEFAULT 0,
  `augslot3type` tinyint(3) NOT NULL DEFAULT 0,
  `augslot3visible` tinyint(3) NOT NULL DEFAULT 0,
  `augslot4type` tinyint(3) NOT NULL DEFAULT 0,
  `augslot4visible` tinyint(3) NOT NULL DEFAULT 0,
  `augslot5type` tinyint(3) NOT NULL DEFAULT 0,
  `augslot5visible` tinyint(3) NOT NULL DEFAULT 0,
  `augslot6type` tinyint(3) NOT NULL DEFAULT 0,
  `augslot6visible` tinyint(3) NOT NULL DEFAULT 0,
  `augtype` int(11) NOT NULL DEFAULT 0,
  `avoidance` int(11) NOT NULL DEFAULT 0,
  `awis` int(11) NOT NULL DEFAULT 0,
  `bagsize` int(11) NOT NULL DEFAULT 0,
  `bagslots` int(11) NOT NULL DEFAULT 0,
  `bagtype` int(11) NOT NULL DEFAULT 0,
  `bagwr` int(11) NOT NULL DEFAULT 0,
  `banedmgamt` int(11) NOT NULL DEFAULT 0,
  `banedmgraceamt` int(11) NOT NULL DEFAULT 0,
  `banedmgbody` int(11) NOT NULL DEFAULT 0,
  `banedmgrace` int(11) NOT NULL DEFAULT 0,
  `bardtype` int(11) NOT NULL DEFAULT 0,
  `bardvalue` int(11) NOT NULL DEFAULT 0,
  `book` int(11) NOT NULL DEFAULT 0,
  `casttime` int(11) NOT NULL DEFAULT 0,
  `casttime_` int(11) NOT NULL DEFAULT 0,
  `charmfile` varchar(32) NOT NULL DEFAULT '',
  `charmfileid` varchar(32) NOT NULL DEFAULT '',
  `classes` int(11) NOT NULL DEFAULT 0,
  `color` int(10) unsigned NOT NULL DEFAULT 0,
  `combateffects` varchar(10) NOT NULL DEFAULT '',
  `extradmgskill` int(11) NOT NULL DEFAULT 0,
  `extradmgamt` int(11) NOT NULL DEFAULT 0,
  `price` int(11) NOT NULL DEFAULT 0,
  `cr` int(11) NOT NULL DEFAULT 0,
  `damage` int(11) NOT NULL DEFAULT 0,
  `damageshield` int(11) NOT NULL DEFAULT 0,
  `deity` int(11) NOT NULL DEFAULT 0,
  `delay` int(11) NOT NULL DEFAULT 0,
  `augdistiller` int(11) unsigned NOT NULL DEFAULT 0,
  `dotshielding` int(11) NOT NULL DEFAULT 0,
  `dr` int(11) NOT NULL DEFAULT 0,
  `clicktype` int(11) NOT NULL DEFAULT 0,
  `clicklevel2` int(11) NOT NULL DEFAULT 0,
  `elemdmgtype` int(11) NOT NULL DEFAULT 0,
  `elemdmgamt` int(11) NOT NULL DEFAULT 0,
  `endur` int(11) NOT NULL DEFAULT 0,
  `factionamt1` int(11) NOT NULL DEFAULT 0,
  `factionamt2` int(11) NOT NULL DEFAULT 0,
  `factionamt3` int(11) NOT NULL DEFAULT 0,
  `factionamt4` int(11) NOT NULL DEFAULT 0,
  `factionmod1` int(11) NOT NULL DEFAULT 0,
  `factionmod2` int(11) NOT NULL DEFAULT 0,
  `factionmod3` int(11) NOT NULL DEFAULT 0,
  `factionmod4` int(11) NOT NULL DEFAULT 0,
  `filename` varchar(32) NOT NULL DEFAULT '',
  `focuseffect` int(11) NOT NULL DEFAULT 0,
  `fr` int(11) NOT NULL DEFAULT 0,
  `fvnodrop` int(11) NOT NULL DEFAULT 0,
  `haste` int(11) NOT NULL DEFAULT 0,
  `clicklevel` int(11) NOT NULL DEFAULT 0,
  `hp` int(11) NOT NULL DEFAULT 0,
  `regen` int(11) NOT NULL DEFAULT 0,
  `icon` int(11) NOT NULL DEFAULT 0,
  `idfile` varchar(30) NOT NULL DEFAULT '',
  `itemclass` int(11) NOT NULL DEFAULT 0,
  `itemtype` int(11) NOT NULL DEFAULT 0,
  `ldonprice` int(11) NOT NULL DEFAULT 0,
  `ldontheme` int(11) NOT NULL DEFAULT 0,
  `ldonsold` int(11) NOT NULL DEFAULT 0,
  `light` int(11) NOT NULL DEFAULT 0,
  `lore` varchar(80) NOT NULL DEFAULT '',
  `loregroup` int(11) NOT NULL DEFAULT 0,
  `magic` int(11) NOT NULL DEFAULT 0,
  `mana` int(11) NOT NULL DEFAULT 0,
  `manaregen` int(11) NOT NULL DEFAULT 0,
  `enduranceregen` int(11) NOT NULL DEFAULT 0,
  `material` int(11) NOT NULL DEFAULT 0,
  `herosforgemodel` int(11) NOT NULL DEFAULT 0,
  `maxcharges` int(11) NOT NULL DEFAULT 0,
  `mr` int(11) NOT NULL DEFAULT 0,
  `nodrop` int(11) NOT NULL DEFAULT 0,
  `norent` int(11) NOT NULL DEFAULT 0,
  `pendingloreflag` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `pr` int(11) NOT NULL DEFAULT 0,
  `procrate` int(11) NOT NULL DEFAULT 0,
  `races` int(11) NOT NULL DEFAULT 0,
  `range` int(11) NOT NULL DEFAULT 0,
  `reclevel` int(11) NOT NULL DEFAULT 0,
  `recskill` int(11) NOT NULL DEFAULT 0,
  `reqlevel` int(11) NOT NULL DEFAULT 0,
  `sellrate` float NOT NULL DEFAULT 0,
  `shielding` int(11) NOT NULL DEFAULT 0,
  `size` int(11) NOT NULL DEFAULT 0,
  `skillmodtype` int(11) NOT NULL DEFAULT 0,
  `skillmodvalue` int(11) NOT NULL DEFAULT 0,
  `slots` int(11) NOT NULL DEFAULT 0,
  `clickeffect` int(11) NOT NULL DEFAULT 0,
  `spellshield` int(11) NOT NULL DEFAULT 0,
  `strikethrough` int(11) NOT NULL DEFAULT 0,
  `stunresist` int(11) NOT NULL DEFAULT 0,
  `summonedflag` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `tradeskills` int(11) NOT NULL DEFAULT 0,
  `favor` int(11) NOT NULL DEFAULT 0,
  `weight` int(11) NOT NULL DEFAULT 0,
  `UNK012` int(11) NOT NULL DEFAULT 0,
  `UNK013` int(11) NOT NULL DEFAULT 0,
  `benefitflag` int(11) NOT NULL DEFAULT 0,
  `UNK054` int(11) NOT NULL DEFAULT 0,
  `UNK059` int(11) NOT NULL DEFAULT 0,
  `booktype` int(11) NOT NULL DEFAULT 0,
  `recastdelay` int(11) NOT NULL DEFAULT 0,
  `recasttype` int(11) NOT NULL DEFAULT 0,
  `guildfavor` int(11) NOT NULL DEFAULT 0,
  `UNK123` int(11) NOT NULL DEFAULT 0,
  `UNK124` int(11) NOT NULL DEFAULT 0,
  `attuneable` int(11) NOT NULL DEFAULT 0,
  `nopet` int(11) NOT NULL DEFAULT 0,
  `updated` datetime DEFAULT NULL,
  `comment` varchar(255) NOT NULL DEFAULT '',
  `UNK127` int(11) NOT NULL DEFAULT 0,
  `pointtype` int(11) NOT NULL DEFAULT 0,
  `potionbelt` int(11) NOT NULL DEFAULT 0,
  `potionbeltslots` int(11) NOT NULL DEFAULT 0,
  `stacksize` int(11) NOT NULL DEFAULT 0,
  `notransfer` int(11) NOT NULL DEFAULT 0,
  `stackable` int(11) NOT NULL DEFAULT 0,
  `UNK134` varchar(255) NOT NULL DEFAULT '',
  `UNK137` int(11) NOT NULL DEFAULT 0,
  `proceffect` int(11) NOT NULL DEFAULT 0,
  `proctype` int(11) NOT NULL DEFAULT 0,
  `proclevel2` int(11) NOT NULL DEFAULT 0,
  `proclevel` int(11) NOT NULL DEFAULT 0,
  `UNK142` int(11) NOT NULL DEFAULT 0,
  `worneffect` int(11) NOT NULL DEFAULT 0,
  `worntype` int(11) NOT NULL DEFAULT 0,
  `wornlevel2` int(11) NOT NULL DEFAULT 0,
  `wornlevel` int(11) NOT NULL DEFAULT 0,
  `UNK147` int(11) NOT NULL DEFAULT 0,
  `focustype` int(11) NOT NULL DEFAULT 0,
  `focuslevel2` int(11) NOT NULL DEFAULT 0,
  `focuslevel` int(11) NOT NULL DEFAULT 0,
  `UNK152` int(11) NOT NULL DEFAULT 0,
  `scrolleffect` int(11) NOT NULL DEFAULT 0,
  `scrolltype` int(11) NOT NULL DEFAULT 0,
  `scrolllevel2` int(11) NOT NULL DEFAULT 0,
  `scrolllevel` int(11) NOT NULL DEFAULT 0,
  `UNK157` int(11) NOT NULL DEFAULT 0,
  `serialized` datetime DEFAULT NULL,
  `verified` datetime DEFAULT NULL,
  `serialization` text DEFAULT NULL,
  `source` varchar(20) NOT NULL DEFAULT '',
  `UNK033` int(11) NOT NULL DEFAULT 0,
  `lorefile` varchar(32) NOT NULL DEFAULT '',
  `UNK014` int(11) NOT NULL DEFAULT 0,
  `svcorruption` int(11) NOT NULL DEFAULT 0,
  `skillmodmax` int(11) NOT NULL DEFAULT 0,
  `UNK060` int(11) NOT NULL DEFAULT 0,
  `augslot1unk2` int(11) NOT NULL DEFAULT 0,
  `augslot2unk2` int(11) NOT NULL DEFAULT 0,
  `augslot3unk2` int(11) NOT NULL DEFAULT 0,
  `augslot4unk2` int(11) NOT NULL DEFAULT 0,
  `augslot5unk2` int(11) NOT NULL DEFAULT 0,
  `augslot6unk2` int(11) NOT NULL DEFAULT 0,
  `UNK120` int(11) NOT NULL DEFAULT 0,
  `UNK121` int(11) NOT NULL DEFAULT 0,
  `questitemflag` int(11) NOT NULL DEFAULT 0,
  `UNK132` text CHARACTER SET utf8 DEFAULT NULL,
  `clickunk5` int(11) NOT NULL DEFAULT 0,
  `clickunk6` varchar(32) NOT NULL DEFAULT '',
  `clickunk7` int(11) NOT NULL DEFAULT 0,
  `procunk1` int(11) NOT NULL DEFAULT 0,
  `procunk2` int(11) NOT NULL DEFAULT 0,
  `procunk3` int(11) NOT NULL DEFAULT 0,
  `procunk4` int(11) NOT NULL DEFAULT 0,
  `procunk6` varchar(32) NOT NULL DEFAULT '',
  `procunk7` int(11) NOT NULL DEFAULT 0,
  `wornunk1` int(11) NOT NULL DEFAULT 0,
  `wornunk2` int(11) NOT NULL DEFAULT 0,
  `wornunk3` int(11) NOT NULL DEFAULT 0,
  `wornunk4` int(11) NOT NULL DEFAULT 0,
  `wornunk5` int(11) NOT NULL DEFAULT 0,
  `wornunk6` varchar(32) NOT NULL DEFAULT '',
  `wornunk7` int(11) NOT NULL DEFAULT 0,
  `focusunk1` int(11) NOT NULL DEFAULT 0,
  `focusunk2` int(11) NOT NULL DEFAULT 0,
  `focusunk3` int(11) NOT NULL DEFAULT 0,
  `focusunk4` int(11) NOT NULL DEFAULT 0,
  `focusunk5` int(11) NOT NULL DEFAULT 0,
  `focusunk6` varchar(32) NOT NULL DEFAULT '',
  `focusunk7` int(11) NOT NULL DEFAULT 0,
  `scrollunk1` int(11) unsigned NOT NULL DEFAULT 0,
  `scrollunk2` int(11) NOT NULL DEFAULT 0,
  `scrollunk3` int(11) NOT NULL DEFAULT 0,
  `scrollunk4` int(11) NOT NULL DEFAULT 0,
  `scrollunk5` int(11) NOT NULL DEFAULT 0,
  `scrollunk6` varchar(32) NOT NULL DEFAULT '',
  `scrollunk7` int(11) NOT NULL DEFAULT 0,
  `UNK193` int(11) NOT NULL DEFAULT 0,
  `purity` int(11) NOT NULL DEFAULT 0,
  `evoitem` int(11) NOT NULL DEFAULT 0,
  `evoid` int(11) NOT NULL DEFAULT 0,
  `evolvinglevel` int(11) NOT NULL DEFAULT 0,
  `evomax` int(11) NOT NULL DEFAULT 0,
  `clickname` varchar(64) NOT NULL DEFAULT '',
  `procname` varchar(64) NOT NULL DEFAULT '',
  `wornname` varchar(64) NOT NULL DEFAULT '',
  `focusname` varchar(64) NOT NULL DEFAULT '',
  `scrollname` varchar(64) NOT NULL DEFAULT '',
  `dsmitigation` smallint(6) NOT NULL DEFAULT 0,
  `heroic_str` smallint(6) NOT NULL DEFAULT 0,
  `heroic_int` smallint(6) NOT NULL DEFAULT 0,
  `heroic_wis` smallint(6) NOT NULL DEFAULT 0,
  `heroic_agi` smallint(6) NOT NULL DEFAULT 0,
  `heroic_dex` smallint(6) NOT NULL DEFAULT 0,
  `heroic_sta` smallint(6) NOT NULL DEFAULT 0,
  `heroic_cha` smallint(6) NOT NULL DEFAULT 0,
  `heroic_pr` smallint(6) NOT NULL DEFAULT 0,
  `heroic_dr` smallint(6) NOT NULL DEFAULT 0,
  `heroic_fr` smallint(6) NOT NULL DEFAULT 0,
  `heroic_cr` smallint(6) NOT NULL DEFAULT 0,
  `heroic_mr` smallint(6) NOT NULL DEFAULT 0,
  `heroic_svcorrup` smallint(6) NOT NULL DEFAULT 0,
  `healamt` smallint(6) NOT NULL DEFAULT 0,
  `spelldmg` smallint(6) NOT NULL DEFAULT 0,
  `clairvoyance` smallint(6) NOT NULL DEFAULT 0,
  `backstabdmg` smallint(6) NOT NULL DEFAULT 0,
  `created` varchar(64) NOT NULL DEFAULT '',
  `elitematerial` smallint(6) NOT NULL DEFAULT 0,
  `ldonsellbackrate` smallint(6) NOT NULL DEFAULT 0,
  `scriptfileid` mediumint(6) NOT NULL DEFAULT 0,
  `expendablearrow` smallint(6) NOT NULL DEFAULT 0,
  `powersourcecapacity` mediumint(7) NOT NULL DEFAULT 0,
  `bardeffect` mediumint(6) NOT NULL DEFAULT 0,
  `bardeffecttype` smallint(6) NOT NULL DEFAULT 0,
  `bardlevel2` smallint(6) NOT NULL DEFAULT 0,
  `bardlevel` smallint(6) NOT NULL DEFAULT 0,
  `bardunk1` smallint(6) NOT NULL DEFAULT 0,
  `bardunk2` smallint(6) NOT NULL DEFAULT 0,
  `bardunk3` smallint(6) NOT NULL DEFAULT 0,
  `bardunk4` smallint(6) NOT NULL DEFAULT 0,
  `bardunk5` smallint(6) NOT NULL DEFAULT 0,
  `bardname` varchar(64) NOT NULL DEFAULT '',
  `bardunk7` smallint(6) NOT NULL DEFAULT 0,
  `UNK214` smallint(6) NOT NULL DEFAULT 0,
  `subtype` int(11) NOT NULL DEFAULT 0,
  `UNK220` int(11) NOT NULL DEFAULT 0,
  `UNK221` int(11) NOT NULL DEFAULT 0,
  `heirloom` int(11) NOT NULL DEFAULT 0,
  `UNK223` int(11) NOT NULL DEFAULT 0,
  `UNK224` int(11) NOT NULL DEFAULT 0,
  `UNK225` int(11) NOT NULL DEFAULT 0,
  `UNK226` int(11) NOT NULL DEFAULT 0,
  `UNK227` int(11) NOT NULL DEFAULT 0,
  `UNK228` int(11) NOT NULL DEFAULT 0,
  `UNK229` int(11) NOT NULL DEFAULT 0,
  `UNK230` int(11) NOT NULL DEFAULT 0,
  `UNK231` int(11) NOT NULL DEFAULT 0,
  `UNK232` int(11) NOT NULL DEFAULT 0,
  `UNK233` int(11) NOT NULL DEFAULT 0,
  `UNK234` int(11) NOT NULL DEFAULT 0,
  `placeable` int(11) NOT NULL DEFAULT 0,
  `UNK236` int(11) NOT NULL DEFAULT 0,
  `UNK237` int(11) NOT NULL DEFAULT 0,
  `UNK238` int(11) NOT NULL DEFAULT 0,
  `UNK239` int(11) NOT NULL DEFAULT 0,
  `UNK240` int(11) NOT NULL DEFAULT 0,
  `UNK241` int(11) NOT NULL DEFAULT 0,
  `epicitem` int(11) NOT NULL DEFAULT 0,
  UNIQUE KEY `ID` (`id`),
  KEY `name_idx` (`Name`),
  KEY `lore_idx` (`lore`),
  KEY `minstatus` (`minstatus`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

CREATE TABLE `npc_types` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` text NOT NULL,
  `lastname` varchar(32) DEFAULT NULL,
  `level` tinyint(2) unsigned NOT NULL DEFAULT 0,
  `race` smallint(5) unsigned NOT NULL DEFAULT 0,
  `class` tinyint(2) unsigned NOT NULL DEFAULT 0,
  `bodytype` int(11) NOT NULL DEFAULT 1,
  `hp` bigint(20) NOT NULL DEFAULT 0,
  `mana` bigint(20) NOT NULL DEFAULT 0,
  `gender` tinyint(2) unsigned NOT NULL DEFAULT 0,
  `texture` tinyint(2) unsigned NOT NULL DEFAULT 0,
  `helmtexture` tinyint(2) unsigned NOT NULL DEFAULT 0,
  `herosforgemodel` int(11) NOT NULL DEFAULT 0,
  `size` float NOT NULL DEFAULT 0,
  `hp_regen_rate` bigint(20) NOT NULL DEFAULT 0,
  `hp_regen_per_second` bigint(20) NOT NULL DEFAULT 0,
  `mana_regen_rate` bigint(20) NOT NULL DEFAULT 0,
  `loottable_id` int(11) unsigned NOT NULL DEFAULT 0,
  `merchant_id` int(11) unsigned NOT NULL DEFAULT 0,
  `alt_currency_id` int(11) unsigned NOT NULL DEFAULT 0,
  `npc_spells_id` int(11) unsigned NOT NULL DEFAULT 0,
  `npc_spells_effects_id` int(11) unsigned NOT NULL DEFAULT 0,
  `npc_faction_id` int(11) NOT NULL DEFAULT 0,
  `adventure_template_id` int(10) unsigned NOT NULL DEFAULT 0,
  `trap_template` int(10) unsigned DEFAULT 0,
  `mindmg` int(10) unsigned NOT NULL DEFAULT 0,
  `maxdmg` int(10) unsigned NOT NULL DEFAULT 0,
  `attack_count` smallint(6) NOT NULL DEFAULT -1,
  `npcspecialattks` varchar(36) NOT NULL DEFAULT '',
  `special_abilities` text DEFAULT NULL,
  `aggroradius` int(10) unsigned NOT NULL DEFAULT 0,
  `assistradius` int(10) unsigned NOT NULL DEFAULT 0,
  `face` int(10) unsigned NOT NULL DEFAULT 1,
  `luclin_hairstyle` int(10) unsigned NOT NULL DEFAULT 1,
  `luclin_haircolor` int(10) unsigned NOT NULL DEFAULT 1,
  `luclin_eyecolor` int(10) unsigned NOT NULL DEFAULT 1,
  `luclin_eyecolor2` int(10) unsigned NOT NULL DEFAULT 1,
  `luclin_beardcolor` int(10) unsigned NOT NULL DEFAULT 1,
  `luclin_beard` int(10) unsigned NOT NULL DEFAULT 0,
  `drakkin_heritage` int(10) NOT NULL DEFAULT 0,
  `drakkin_tattoo` int(10) NOT NULL DEFAULT 0,
  `drakkin_details` int(10) NOT NULL DEFAULT 0,
  `armortint_id` int(10) unsigned NOT NULL DEFAULT 0,
  `armortint_red` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `armortint_green` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `armortint_blue` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `d_melee_texture1` int(11) unsigned NOT NULL DEFAULT 0,
  `d_melee_texture2` int(11) unsigned NOT NULL DEFAULT 0,
  `ammo_idfile` varchar(30) NOT NULL DEFAULT 'IT10',
  `prim_melee_type` tinyint(4) unsigned NOT NULL DEFAULT 28,
  `sec_melee_type` tinyint(4) unsigned NOT NULL DEFAULT 28,
  `ranged_type` tinyint(4) unsigned NOT NULL DEFAULT 7,
  `runspeed` float NOT NULL DEFAULT 0,
  `MR` smallint(5) NOT NULL DEFAULT 0,
  `CR` smallint(5) NOT NULL DEFAULT 0,
  `DR` smallint(5) NOT NULL DEFAULT 0,
  `FR` smallint(5) NOT NULL DEFAULT 0,
  `PR` smallint(5) NOT NULL DEFAULT 0,
  `Corrup` smallint(5) NOT NULL DEFAULT 0,
  `PhR` smallint(5) unsigned NOT NULL DEFAULT 0,
  `see_invis` smallint(4) NOT NULL DEFAULT 0,
  `see_invis_undead` smallint(4) NOT NULL DEFAULT 0,
  `qglobal` int(2) unsigned NOT NULL DEFAULT 0,
  `AC` smallint(5) NOT NULL DEFAULT 0,
  `npc_aggro` tinyint(4) NOT NULL DEFAULT 0,
  `spawn_limit` tinyint(4) NOT NULL DEFAULT 0,
  `attack_speed` float NOT NULL DEFAULT 0,
  `attack_delay` tinyint(3) unsigned NOT NULL DEFAULT 30,
  `findable` tinyint(4) NOT NULL DEFAULT 0,
  `STR` mediumint(8) unsigned NOT NULL DEFAULT 75,
  `STA` mediumint(8) unsigned NOT NULL DEFAULT 75,
  `DEX` mediumint(8) unsigned NOT NULL DEFAULT 75,
  `AGI` mediumint(8) unsigned NOT NULL DEFAULT 75,
  `_INT` mediumint(8) unsigned NOT NULL DEFAULT 80,
  `WIS` mediumint(8) unsigned NOT NULL DEFAULT 75,
  `CHA` mediumint(8) unsigned NOT NULL DEFAULT 75,
  `see_hide` tinyint(4) NOT NULL DEFAULT 0,
  `see_improved_hide` tinyint(4) NOT NULL DEFAULT 0,
  `trackable` tinyint(4) NOT NULL DEFAULT 1,
  `isbot` tinyint(4) NOT NULL DEFAULT 0,
  `exclude` tinyint(4) NOT NULL DEFAULT 1,
  `ATK` mediumint(9) NOT NULL DEFAULT 0,
  `Accuracy` mediumint(9) NOT NULL DEFAULT 0,
  `Avoidance` mediumint(9) unsigned NOT NULL DEFAULT 0,
  `slow_mitigation` smallint(4) NOT NULL DEFAULT 0,
  `version` smallint(5) unsigned NOT NULL DEFAULT 0,
  `maxlevel` tinyint(3) NOT NULL DEFAULT 0,
  `scalerate` int(11) NOT NULL DEFAULT 100,
  `private_corpse` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `unique_spawn_by_name` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `underwater` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `isquest` tinyint(3) NOT NULL DEFAULT 0,
  `emoteid` int(10) unsigned NOT NULL DEFAULT 0,
  `spellscale` float NOT NULL DEFAULT 100,
  `healscale` float NOT NULL DEFAULT 100,
  `no_target_hotkey` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `raid_target` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `armtexture` tinyint(2) NOT NULL DEFAULT 0,
  `bracertexture` tinyint(2) NOT NULL DEFAULT 0,
  `handtexture` tinyint(2) NOT NULL DEFAULT 0,
  `legtexture` tinyint(2) NOT NULL DEFAULT 0,
  `feettexture` tinyint(2) NOT NULL DEFAULT 0,
  `light` tinyint(2) NOT NULL DEFAULT 0,
  `walkspeed` tinyint(2) NOT NULL DEFAULT 0,
  `peqid` int(11) NOT NULL DEFAULT 0,
  `unique_` tinyint(2) NOT NULL DEFAULT 0,
  `fixed` tinyint(2) NOT NULL DEFAULT 0,
  `ignore_despawn` tinyint(2) NOT NULL DEFAULT 0,
  `show_name` tinyint(2) NOT NULL DEFAULT 1,
  `untargetable` tinyint(2) NOT NULL DEFAULT 0,
  `charm_ac` smallint(5) DEFAULT 0,
  `charm_min_dmg` int(10) DEFAULT 0,
  `charm_max_dmg` int(10) DEFAULT 0,
  `charm_attack_delay` tinyint(3) DEFAULT 0,
  `charm_accuracy_rating` mediumint(9) DEFAULT 0,
  `charm_avoidance_rating` mediumint(9) DEFAULT 0,
  `charm_atk` mediumint(9) DEFAULT 0,
  `skip_global_loot` tinyint(4) DEFAULT 0,
  `rare_spawn` tinyint(4) DEFAULT 0,
  `stuck_behavior` tinyint(4) NOT NULL DEFAULT 0,
  `model` smallint(5) NOT NULL DEFAULT 0,
  `flymode` tinyint(4) NOT NULL DEFAULT -1,
  `always_aggro` tinyint(1) NOT NULL DEFAULT 0,
  `exp_mod` int(11) NOT NULL DEFAULT 100,
  `heroic_strikethrough` int(11) NOT NULL DEFAULT 0,
  `faction_amount` int(10) NOT NULL DEFAULT 0,
  `keeps_sold_items` tinyint(1) unsigned NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2000911 DEFAULT CHARSET=latin1 PACK_KEYS=0;
/*!40101 SET character_set_client = @saved_cs_client */;

CREATE TABLE `character_data` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL DEFAULT 0,
  `name` varchar(64) NOT NULL DEFAULT '',
  `last_name` varchar(64) NOT NULL DEFAULT '',
  `title` varchar(32) NOT NULL DEFAULT '',
  `suffix` varchar(32) NOT NULL DEFAULT '',
  `zone_id` int(11) unsigned NOT NULL DEFAULT 0,
  `zone_instance` int(11) unsigned NOT NULL DEFAULT 0,
  `y` float NOT NULL DEFAULT 0,
  `x` float NOT NULL DEFAULT 0,
  `z` float NOT NULL DEFAULT 0,
  `heading` float NOT NULL DEFAULT 0,
  `gender` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `race` smallint(11) unsigned NOT NULL DEFAULT 0,
  `class` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `level` int(11) unsigned NOT NULL DEFAULT 0,
  `deity` int(11) unsigned NOT NULL DEFAULT 0,
  `birthday` int(11) unsigned NOT NULL DEFAULT 0,
  `last_login` int(11) unsigned NOT NULL DEFAULT 0,
  `time_played` int(11) unsigned NOT NULL DEFAULT 0,
  `level2` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `anon` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `gm` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `face` int(11) unsigned NOT NULL DEFAULT 0,
  `hair_color` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `hair_style` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `beard` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `beard_color` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `eye_color_1` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `eye_color_2` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `drakkin_heritage` int(11) unsigned NOT NULL DEFAULT 0,
  `drakkin_tattoo` int(11) unsigned NOT NULL DEFAULT 0,
  `drakkin_details` int(11) unsigned NOT NULL DEFAULT 0,
  `ability_time_seconds` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `ability_number` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `ability_time_minutes` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `ability_time_hours` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `exp` int(11) unsigned NOT NULL DEFAULT 0,
  `exp_enabled` tinyint(1) unsigned NOT NULL DEFAULT 1,
  `aa_points_spent` int(11) unsigned NOT NULL DEFAULT 0,
  `aa_exp` int(11) unsigned NOT NULL DEFAULT 0,
  `aa_points` int(11) unsigned NOT NULL DEFAULT 0,
  `group_leadership_exp` int(11) unsigned NOT NULL DEFAULT 0,
  `raid_leadership_exp` int(11) unsigned NOT NULL DEFAULT 0,
  `group_leadership_points` int(11) unsigned NOT NULL DEFAULT 0,
  `raid_leadership_points` int(11) unsigned NOT NULL DEFAULT 0,
  `points` int(11) unsigned NOT NULL DEFAULT 0,
  `cur_hp` int(11) unsigned NOT NULL DEFAULT 0,
  `mana` int(11) unsigned NOT NULL DEFAULT 0,
  `endurance` int(11) unsigned NOT NULL DEFAULT 0,
  `intoxication` int(11) unsigned NOT NULL DEFAULT 0,
  `str` int(11) unsigned NOT NULL DEFAULT 0,
  `sta` int(11) unsigned NOT NULL DEFAULT 0,
  `cha` int(11) unsigned NOT NULL DEFAULT 0,
  `dex` int(11) unsigned NOT NULL DEFAULT 0,
  `int` int(11) unsigned NOT NULL DEFAULT 0,
  `agi` int(11) unsigned NOT NULL DEFAULT 0,
  `wis` int(11) unsigned NOT NULL DEFAULT 0,
  `zone_change_count` int(11) unsigned NOT NULL DEFAULT 0,
  `toxicity` int(11) unsigned NOT NULL DEFAULT 0,
  `hunger_level` int(11) unsigned NOT NULL DEFAULT 0,
  `thirst_level` int(11) unsigned NOT NULL DEFAULT 0,
  `ability_up` int(11) unsigned NOT NULL DEFAULT 0,
  `ldon_points_guk` int(11) unsigned NOT NULL DEFAULT 0,
  `ldon_points_mir` int(11) unsigned NOT NULL DEFAULT 0,
  `ldon_points_mmc` int(11) unsigned NOT NULL DEFAULT 0,
  `ldon_points_ruj` int(11) unsigned NOT NULL DEFAULT 0,
  `ldon_points_tak` int(11) unsigned NOT NULL DEFAULT 0,
  `ldon_points_available` int(11) unsigned NOT NULL DEFAULT 0,
  `tribute_time_remaining` int(11) unsigned NOT NULL DEFAULT 0,
  `career_tribute_points` int(11) unsigned NOT NULL DEFAULT 0,
  `tribute_points` int(11) unsigned NOT NULL DEFAULT 0,
  `tribute_active` int(11) unsigned NOT NULL DEFAULT 0,
  `pvp_status` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `pvp_kills` int(11) unsigned NOT NULL DEFAULT 0,
  `pvp_deaths` int(11) unsigned NOT NULL DEFAULT 0,
  `pvp_current_points` int(11) unsigned NOT NULL DEFAULT 0,
  `pvp_career_points` int(11) unsigned NOT NULL DEFAULT 0,
  `pvp_best_kill_streak` int(11) unsigned NOT NULL DEFAULT 0,
  `pvp_worst_death_streak` int(11) unsigned NOT NULL DEFAULT 0,
  `pvp_current_kill_streak` int(11) unsigned NOT NULL DEFAULT 0,
  `pvp2` int(11) unsigned NOT NULL DEFAULT 0,
  `pvp_type` int(11) unsigned NOT NULL DEFAULT 0,
  `show_helm` int(11) unsigned NOT NULL DEFAULT 0,
  `group_auto_consent` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `raid_auto_consent` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `guild_auto_consent` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `leadership_exp_on` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `RestTimer` int(11) unsigned NOT NULL DEFAULT 0,
  `air_remaining` int(11) unsigned NOT NULL DEFAULT 0,
  `autosplit_enabled` int(11) unsigned NOT NULL DEFAULT 0,
  `lfp` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `lfg` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `mailkey` char(16) NOT NULL DEFAULT '',
  `xtargets` tinyint(3) unsigned NOT NULL DEFAULT 5,
  `firstlogon` tinyint(3) NOT NULL DEFAULT 0,
  `e_aa_effects` int(11) unsigned NOT NULL DEFAULT 0,
  `e_percent_to_aa` int(11) unsigned NOT NULL DEFAULT 0,
  `e_expended_aa_spent` int(11) unsigned NOT NULL DEFAULT 0,
  `aa_points_spent_old` int(11) unsigned NOT NULL DEFAULT 0,
  `aa_points_old` int(11) unsigned NOT NULL DEFAULT 0,
  `e_last_invsnapshot` int(11) unsigned NOT NULL DEFAULT 0,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `account_id` (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE
  `discovered_items` (
    `item_id` int(11) unsigned NOT NULL DEFAULT 0,
    `char_name` varchar(64) NOT NULL DEFAULT '',
    `discovered_date` int(11) unsigned NOT NULL DEFAULT 0,
    `account_status` int(11) NOT NULL DEFAULT 0,
    PRIMARY KEY (`item_id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COLLATE = latin1_swedish_ci;


CREATE TABLE
  `spells_new` (
    `id` int(11) NOT NULL DEFAULT 0,
    `name` varchar(64) DEFAULT NULL,
    `player_1` varchar(64) DEFAULT 'BLUE_TRAIL',
    `teleport_zone` varchar(64) DEFAULT NULL,
    `you_cast` varchar(120) DEFAULT NULL,
    `other_casts` varchar(120) DEFAULT NULL,
    `cast_on_you` varchar(120) DEFAULT NULL,
    `cast_on_other` varchar(120) DEFAULT NULL,
    `spell_fades` varchar(120) DEFAULT NULL,
    `range` int(11) NOT NULL DEFAULT 100,
    `aoerange` int(11) NOT NULL DEFAULT 0,
    `pushback` int(11) NOT NULL DEFAULT 0,
    `pushup` int(11) NOT NULL DEFAULT 0,
    `cast_time` int(11) NOT NULL DEFAULT 0,
    `recovery_time` int(11) NOT NULL DEFAULT 0,
    `recast_time` int(11) NOT NULL DEFAULT 0,
    `buffdurationformula` int(11) NOT NULL DEFAULT 7,
    `buffduration` int(11) NOT NULL DEFAULT 65,
    `AEDuration` int(11) NOT NULL DEFAULT 0,
    `mana` int(11) NOT NULL DEFAULT 0,
    `effect_base_value1` int(11) NOT NULL DEFAULT 100,
    `effect_base_value2` int(11) NOT NULL DEFAULT 0,
    `effect_base_value3` int(11) NOT NULL DEFAULT 0,
    `effect_base_value4` int(11) NOT NULL DEFAULT 0,
    `effect_base_value5` int(11) NOT NULL DEFAULT 0,
    `effect_base_value6` int(11) NOT NULL DEFAULT 0,
    `effect_base_value7` int(11) NOT NULL DEFAULT 0,
    `effect_base_value8` int(11) NOT NULL DEFAULT 0,
    `effect_base_value9` int(11) NOT NULL DEFAULT 0,
    `effect_base_value10` int(11) NOT NULL DEFAULT 0,
    `effect_base_value11` int(11) NOT NULL DEFAULT 0,
    `effect_base_value12` int(11) NOT NULL DEFAULT 0,
    `effect_limit_value1` int(11) NOT NULL DEFAULT 0,
    `effect_limit_value2` int(11) NOT NULL DEFAULT 0,
    `effect_limit_value3` int(11) NOT NULL DEFAULT 0,
    `effect_limit_value4` int(11) NOT NULL DEFAULT 0,
    `effect_limit_value5` int(11) NOT NULL DEFAULT 0,
    `effect_limit_value6` int(11) NOT NULL DEFAULT 0,
    `effect_limit_value7` int(11) NOT NULL DEFAULT 0,
    `effect_limit_value8` int(11) NOT NULL DEFAULT 0,
    `effect_limit_value9` int(11) NOT NULL DEFAULT 0,
    `effect_limit_value10` int(11) NOT NULL DEFAULT 0,
    `effect_limit_value11` int(11) NOT NULL DEFAULT 0,
    `effect_limit_value12` int(11) NOT NULL DEFAULT 0,
    `max1` int(11) NOT NULL DEFAULT 0,
    `max2` int(11) NOT NULL DEFAULT 0,
    `max3` int(11) NOT NULL DEFAULT 0,
    `max4` int(11) NOT NULL DEFAULT 0,
    `max5` int(11) NOT NULL DEFAULT 0,
    `max6` int(11) NOT NULL DEFAULT 0,
    `max7` int(11) NOT NULL DEFAULT 0,
    `max8` int(11) NOT NULL DEFAULT 0,
    `max9` int(11) NOT NULL DEFAULT 0,
    `max10` int(11) NOT NULL DEFAULT 0,
    `max11` int(11) NOT NULL DEFAULT 0,
    `max12` int(11) NOT NULL DEFAULT 0,
    `icon` int(11) NOT NULL DEFAULT 0,
    `memicon` int(11) NOT NULL DEFAULT 0,
    `components1` int(11) NOT NULL DEFAULT -1,
    `components2` int(11) NOT NULL DEFAULT -1,
    `components3` int(11) NOT NULL DEFAULT -1,
    `components4` int(11) NOT NULL DEFAULT -1,
    `component_counts1` int(11) NOT NULL DEFAULT 1,
    `component_counts2` int(11) NOT NULL DEFAULT 1,
    `component_counts3` int(11) NOT NULL DEFAULT 1,
    `component_counts4` int(11) NOT NULL DEFAULT 1,
    `NoexpendReagent1` int(11) NOT NULL DEFAULT -1,
    `NoexpendReagent2` int(11) NOT NULL DEFAULT -1,
    `NoexpendReagent3` int(11) NOT NULL DEFAULT -1,
    `NoexpendReagent4` int(11) NOT NULL DEFAULT -1,
    `formula1` int(11) NOT NULL DEFAULT 100,
    `formula2` int(11) NOT NULL DEFAULT 100,
    `formula3` int(11) NOT NULL DEFAULT 100,
    `formula4` int(11) NOT NULL DEFAULT 100,
    `formula5` int(11) NOT NULL DEFAULT 100,
    `formula6` int(11) NOT NULL DEFAULT 100,
    `formula7` int(11) NOT NULL DEFAULT 100,
    `formula8` int(11) NOT NULL DEFAULT 100,
    `formula9` int(11) NOT NULL DEFAULT 100,
    `formula10` int(11) NOT NULL DEFAULT 100,
    `formula11` int(11) NOT NULL DEFAULT 100,
    `formula12` int(11) NOT NULL DEFAULT 100,
    `LightType` int(11) NOT NULL DEFAULT 0,
    `goodEffect` int(11) NOT NULL DEFAULT 0,
    `Activated` int(11) NOT NULL DEFAULT 0,
    `resisttype` int(11) NOT NULL DEFAULT 0,
    `effectid1` int(11) NOT NULL DEFAULT 254,
    `effectid2` int(11) NOT NULL DEFAULT 254,
    `effectid3` int(11) NOT NULL DEFAULT 254,
    `effectid4` int(11) NOT NULL DEFAULT 254,
    `effectid5` int(11) NOT NULL DEFAULT 254,
    `effectid6` int(11) NOT NULL DEFAULT 254,
    `effectid7` int(11) NOT NULL DEFAULT 254,
    `effectid8` int(11) NOT NULL DEFAULT 254,
    `effectid9` int(11) NOT NULL DEFAULT 254,
    `effectid10` int(11) NOT NULL DEFAULT 254,
    `effectid11` int(11) NOT NULL DEFAULT 254,
    `effectid12` int(11) NOT NULL DEFAULT 254,
    `targettype` int(11) NOT NULL DEFAULT 2,
    `basediff` int(11) NOT NULL DEFAULT 0,
    `skill` int(11) NOT NULL DEFAULT 98,
    `zonetype` int(11) NOT NULL DEFAULT -1,
    `EnvironmentType` int(11) NOT NULL DEFAULT 0,
    `TimeOfDay` int(11) NOT NULL DEFAULT 0,
    `classes1` int(11) NOT NULL DEFAULT 255,
    `classes2` int(11) NOT NULL DEFAULT 255,
    `classes3` int(11) NOT NULL DEFAULT 255,
    `classes4` int(11) NOT NULL DEFAULT 255,
    `classes5` int(11) NOT NULL DEFAULT 255,
    `classes6` int(11) NOT NULL DEFAULT 255,
    `classes7` int(11) NOT NULL DEFAULT 255,
    `classes8` int(11) NOT NULL DEFAULT 255,
    `classes9` int(11) NOT NULL DEFAULT 255,
    `classes10` int(11) NOT NULL DEFAULT 255,
    `classes11` int(11) NOT NULL DEFAULT 255,
    `classes12` int(11) NOT NULL DEFAULT 255,
    `classes13` int(11) NOT NULL DEFAULT 255,
    `classes14` int(11) NOT NULL DEFAULT 255,
    `classes15` int(11) NOT NULL DEFAULT 255,
    `classes16` int(11) NOT NULL DEFAULT 255,
    `CastingAnim` int(11) NOT NULL DEFAULT 44,
    `TargetAnim` int(11) NOT NULL DEFAULT 13,
    `TravelType` int(11) NOT NULL DEFAULT 0,
    `SpellAffectIndex` int(11) NOT NULL DEFAULT -1,
    `disallow_sit` int(11) NOT NULL DEFAULT 0,
    `deities0` int(11) NOT NULL DEFAULT 0,
    `deities1` int(11) NOT NULL DEFAULT 0,
    `deities2` int(11) NOT NULL DEFAULT 0,
    `deities3` int(11) NOT NULL DEFAULT 0,
    `deities4` int(11) NOT NULL DEFAULT 0,
    `deities5` int(11) NOT NULL DEFAULT 0,
    `deities6` int(11) NOT NULL DEFAULT 0,
    `deities7` int(11) NOT NULL DEFAULT 0,
    `deities8` int(11) NOT NULL DEFAULT 0,
    `deities9` int(11) NOT NULL DEFAULT 0,
    `deities10` int(11) NOT NULL DEFAULT 0,
    `deities11` int(11) NOT NULL DEFAULT 0,
    `deities12` int(12) NOT NULL DEFAULT 0,
    `deities13` int(11) NOT NULL DEFAULT 0,
    `deities14` int(11) NOT NULL DEFAULT 0,
    `deities15` int(11) NOT NULL DEFAULT 0,
    `deities16` int(11) NOT NULL DEFAULT 0,
    `field142` int(11) NOT NULL DEFAULT 100,
    `field143` int(11) NOT NULL DEFAULT 0,
    `new_icon` int(11) NOT NULL DEFAULT 161,
    `spellanim` int(11) NOT NULL DEFAULT 0,
    `uninterruptable` int(11) NOT NULL DEFAULT 0,
    `ResistDiff` int(11) NOT NULL DEFAULT -150,
    `dot_stacking_exempt` int(11) NOT NULL DEFAULT 0,
    `deleteable` int(11) NOT NULL DEFAULT 0,
    `RecourseLink` int(11) NOT NULL DEFAULT 0,
    `no_partial_resist` int(11) NOT NULL DEFAULT 0,
    `field152` int(11) NOT NULL DEFAULT 0,
    `field153` int(11) NOT NULL DEFAULT 0,
    `short_buff_box` int(11) NOT NULL DEFAULT -1,
    `descnum` int(11) NOT NULL DEFAULT 0,
    `typedescnum` int(11) DEFAULT NULL,
    `effectdescnum` int(11) DEFAULT NULL,
    `effectdescnum2` int(11) NOT NULL DEFAULT 0,
    `npc_no_los` int(11) NOT NULL DEFAULT 0,
    `field160` int(11) NOT NULL DEFAULT 0,
    `reflectable` int(11) NOT NULL DEFAULT 0,
    `bonushate` int(11) NOT NULL DEFAULT 0,
    `field163` int(11) NOT NULL DEFAULT 100,
    `field164` int(11) NOT NULL DEFAULT -150,
    `ldon_trap` int(11) NOT NULL DEFAULT 0,
    `EndurCost` int(11) NOT NULL DEFAULT 0,
    `EndurTimerIndex` int(11) NOT NULL DEFAULT 0,
    `IsDiscipline` int(11) NOT NULL DEFAULT 0,
    `field169` int(11) NOT NULL DEFAULT 0,
    `field170` int(11) NOT NULL DEFAULT 0,
    `field171` int(11) NOT NULL DEFAULT 0,
    `field172` int(11) NOT NULL DEFAULT 0,
    `HateAdded` int(11) NOT NULL DEFAULT 0,
    `EndurUpkeep` int(11) NOT NULL DEFAULT 0,
    `numhitstype` int(11) NOT NULL DEFAULT 0,
    `numhits` int(11) NOT NULL DEFAULT 0,
    `pvpresistbase` int(11) NOT NULL DEFAULT -150,
    `pvpresistcalc` int(11) NOT NULL DEFAULT 100,
    `pvpresistcap` int(11) NOT NULL DEFAULT -150,
    `spell_category` int(11) NOT NULL DEFAULT -99,
    `pvp_duration` int(11) NOT NULL DEFAULT 0,
    `pvp_duration_cap` int(11) NOT NULL DEFAULT 0,
    `pcnpc_only_flag` int(11) DEFAULT 0,
    `cast_not_standing` int(11) DEFAULT 0,
    `can_mgb` int(11) NOT NULL DEFAULT 0,
    `nodispell` int(11) NOT NULL DEFAULT -1,
    `npc_category` int(11) NOT NULL DEFAULT 0,
    `npc_usefulness` int(11) NOT NULL DEFAULT 0,
    `MinResist` int(11) NOT NULL DEFAULT 0,
    `MaxResist` int(11) NOT NULL DEFAULT 0,
    `viral_targets` int(11) NOT NULL DEFAULT 0,
    `viral_timer` int(11) NOT NULL DEFAULT 0,
    `nimbuseffect` int(11) DEFAULT 0,
    `ConeStartAngle` int(11) NOT NULL DEFAULT 0,
    `ConeStopAngle` int(11) NOT NULL DEFAULT 0,
    `sneaking` int(11) NOT NULL DEFAULT 0,
    `not_extendable` int(11) NOT NULL DEFAULT 0,
    `field198` int(11) NOT NULL DEFAULT 0,
    `field199` int(11) NOT NULL DEFAULT 1,
    `suspendable` int(11) DEFAULT 0,
    `viral_range` int(11) NOT NULL DEFAULT 0,
    `songcap` int(11) DEFAULT 0,
    `field203` int(11) DEFAULT 0,
    `field204` int(11) DEFAULT 0,
    `no_block` int(11) NOT NULL DEFAULT 0,
    `field206` int(11) DEFAULT -1,
    `spellgroup` int(11) DEFAULT 0,
    `rank` int(11) NOT NULL DEFAULT 0,
    `field209` int(11) DEFAULT 0,
    `field210` int(11) DEFAULT 1,
    `CastRestriction` int(11) NOT NULL DEFAULT 0,
    `allowrest` int(11) DEFAULT 0,
    `InCombat` int(11) NOT NULL DEFAULT 0,
    `OutofCombat` int(11) NOT NULL DEFAULT 0,
    `field215` int(11) DEFAULT 0,
    `field216` int(11) DEFAULT 0,
    `field217` int(11) DEFAULT 0,
    `aemaxtargets` int(11) NOT NULL DEFAULT 0,
    `maxtargets` int(11) DEFAULT 0,
    `field220` int(11) DEFAULT 0,
    `field221` int(11) DEFAULT 0,
    `field222` int(11) DEFAULT 0,
    `field223` int(11) DEFAULT 0,
    `persistdeath` int(11) DEFAULT 0,
    `field225` int(11) NOT NULL DEFAULT 0,
    `field226` int(11) NOT NULL DEFAULT 0,
    `min_dist` float NOT NULL DEFAULT 0,
    `min_dist_mod` float NOT NULL DEFAULT 0,
    `max_dist` float NOT NULL DEFAULT 0,
    `max_dist_mod` float NOT NULL DEFAULT 0,
    `min_range` int(11) NOT NULL DEFAULT 0,
    `field232` int(11) NOT NULL DEFAULT 0,
    `field233` int(11) NOT NULL DEFAULT 0,
    `field234` int(11) NOT NULL DEFAULT 0,
    `field235` int(11) NOT NULL DEFAULT 0,
    `field236` int(11) NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COLLATE = latin1_swedish_ci;

CREATE TABLE
`faction_list` (
  `id` int(11) NOT NULL,
  `name` varchar(50) NOT NULL DEFAULT '',
  `base` smallint(6) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb3 COLLATE = utf8mb3_general_ci;

CREATE TABLE
  `npc_faction_entries` (
    `npc_faction_id` int(11) unsigned NOT NULL DEFAULT 0,
    `faction_id` int(11) unsigned NOT NULL DEFAULT 0,
    `value` int(11) NOT NULL DEFAULT 0,
    `npc_value` tinyint(3) NOT NULL DEFAULT 0,
    `temp` tinyint(3) NOT NULL DEFAULT 0,
    PRIMARY KEY (`npc_faction_id`, `faction_id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COLLATE = latin1_swedish_ci;

CREATE TABLE
  `loottable_entries` (
    `loottable_id` int(11) unsigned NOT NULL DEFAULT 0,
    `lootdrop_id` int(11) unsigned NOT NULL DEFAULT 0,
    `multiplier` tinyint(2) unsigned NOT NULL DEFAULT 1,
    `droplimit` tinyint(2) unsigned NOT NULL DEFAULT 0,
    `mindrop` tinyint(2) unsigned NOT NULL DEFAULT 0,
    `probability` float NOT NULL DEFAULT 100,
    PRIMARY KEY (`loottable_id`, `lootdrop_id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COLLATE = latin1_swedish_ci;

CREATE TABLE
  `lootdrop_entries` (
    `lootdrop_id` int(11) unsigned NOT NULL DEFAULT 0,
    `item_id` int(11) NOT NULL DEFAULT 0,
    `item_charges` smallint(2) unsigned NOT NULL DEFAULT 1,
    `equip_item` tinyint(2) unsigned NOT NULL DEFAULT 0,
    `chance` float NOT NULL DEFAULT 1,
    `disabled_chance` float NOT NULL DEFAULT 0,
    `trivial_min_level` smallint(5) unsigned NOT NULL DEFAULT 0,
    `trivial_max_level` smallint(5) unsigned NOT NULL DEFAULT 0,
    `multiplier` tinyint(2) unsigned NOT NULL DEFAULT 1,
    `npc_min_level` smallint(5) unsigned NOT NULL DEFAULT 0,
    `npc_max_level` smallint(5) unsigned NOT NULL DEFAULT 0,
    `min_expansion` tinyint(4) NOT NULL DEFAULT -1,
    `max_expansion` tinyint(4) NOT NULL DEFAULT -1,
    `content_flags` varchar(100) DEFAULT NULL,
    `content_flags_disabled` varchar(100) DEFAULT NULL,
    PRIMARY KEY (`lootdrop_id`, `item_id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COLLATE = latin1_swedish_ci;

CREATE TABLE
  `zone` (
    `id` int(10) NOT NULL AUTO_INCREMENT,
    `zoneidnumber` int(4) NOT NULL DEFAULT 0,
    `version` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `short_name` varchar(32) DEFAULT NULL,
    `long_name` text NOT NULL,
    `min_status` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `map_file_name` varchar(100) DEFAULT NULL,
    `note` varchar(200) DEFAULT NULL,
    `min_expansion` tinyint(4) NOT NULL DEFAULT -1,
    `max_expansion` tinyint(4) NOT NULL DEFAULT -1,
    `content_flags` varchar(100) DEFAULT NULL,
    `content_flags_disabled` varchar(100) DEFAULT NULL,
    `expansion` tinyint(3) NOT NULL DEFAULT 0,
    `file_name` varchar(16) DEFAULT NULL,
    `safe_x` float NOT NULL DEFAULT 0,
    `safe_y` float NOT NULL DEFAULT 0,
    `safe_z` float NOT NULL DEFAULT 0,
    `safe_heading` float NOT NULL DEFAULT 0,
    `graveyard_id` float NOT NULL DEFAULT 0,
    `min_level` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `max_level` tinyint(3) unsigned NOT NULL DEFAULT 255,
    `timezone` int(5) NOT NULL DEFAULT 0,
    `maxclients` int(5) NOT NULL DEFAULT 0,
    `ruleset` int(10) unsigned NOT NULL DEFAULT 0,
    `underworld` float NOT NULL DEFAULT 0,
    `minclip` float NOT NULL DEFAULT 450,
    `maxclip` float NOT NULL DEFAULT 450,
    `fog_minclip` float NOT NULL DEFAULT 450,
    `fog_maxclip` float NOT NULL DEFAULT 450,
    `fog_blue` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `fog_red` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `fog_green` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `sky` tinyint(3) unsigned NOT NULL DEFAULT 1,
    `ztype` tinyint(3) unsigned NOT NULL DEFAULT 1,
    `zone_exp_multiplier` decimal(6, 2) NOT NULL DEFAULT 0.00,
    `walkspeed` float NOT NULL DEFAULT 0.4,
    `time_type` tinyint(3) unsigned NOT NULL DEFAULT 2,
    `fog_red1` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `fog_green1` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `fog_blue1` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `fog_minclip1` float NOT NULL DEFAULT 450,
    `fog_maxclip1` float NOT NULL DEFAULT 450,
    `fog_red2` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `fog_green2` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `fog_blue2` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `fog_minclip2` float NOT NULL DEFAULT 450,
    `fog_maxclip2` float NOT NULL DEFAULT 450,
    `fog_red3` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `fog_green3` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `fog_blue3` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `fog_minclip3` float NOT NULL DEFAULT 450,
    `fog_maxclip3` float NOT NULL DEFAULT 450,
    `fog_red4` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `fog_green4` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `fog_blue4` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `fog_minclip4` float NOT NULL DEFAULT 450,
    `fog_maxclip4` float NOT NULL DEFAULT 450,
    `fog_density` float NOT NULL DEFAULT 0,
    `flag_needed` varchar(128) NOT NULL DEFAULT '',
    `canbind` tinyint(4) NOT NULL DEFAULT 1,
    `cancombat` tinyint(4) NOT NULL DEFAULT 1,
    `canlevitate` tinyint(4) NOT NULL DEFAULT 1,
    `castoutdoor` tinyint(4) NOT NULL DEFAULT 1,
    `hotzone` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `insttype` tinyint(1) unsigned zerofill NOT NULL DEFAULT 0,
    `shutdowndelay` bigint(16) unsigned NOT NULL DEFAULT 5000,
    `peqzone` tinyint(4) NOT NULL DEFAULT 1,
    `bypass_expansion_check` tinyint(3) NOT NULL DEFAULT 0,
    `suspendbuffs` tinyint(1) unsigned NOT NULL DEFAULT 0,
    `rain_chance1` int(4) NOT NULL DEFAULT 0,
    `rain_chance2` int(4) NOT NULL DEFAULT 0,
    `rain_chance3` int(4) NOT NULL DEFAULT 0,
    `rain_chance4` int(4) NOT NULL DEFAULT 0,
    `rain_duration1` int(4) NOT NULL DEFAULT 0,
    `rain_duration2` int(4) NOT NULL DEFAULT 0,
    `rain_duration3` int(4) NOT NULL DEFAULT 0,
    `rain_duration4` int(4) NOT NULL DEFAULT 0,
    `snow_chance1` int(4) NOT NULL DEFAULT 0,
    `snow_chance2` int(4) NOT NULL DEFAULT 0,
    `snow_chance3` int(4) NOT NULL DEFAULT 0,
    `snow_chance4` int(4) NOT NULL DEFAULT 0,
    `snow_duration1` int(4) NOT NULL DEFAULT 0,
    `snow_duration2` int(4) NOT NULL DEFAULT 0,
    `snow_duration3` int(4) NOT NULL DEFAULT 0,
    `snow_duration4` int(4) NOT NULL DEFAULT 0,
    `gravity` float NOT NULL DEFAULT 0.4,
    `type` int(3) NOT NULL DEFAULT 0,
    `skylock` tinyint(4) NOT NULL DEFAULT 0,
    `fast_regen_hp` int(11) NOT NULL DEFAULT 180,
    `fast_regen_mana` int(11) NOT NULL DEFAULT 180,
    `fast_regen_endurance` int(11) NOT NULL DEFAULT 180,
    `npc_max_aggro_dist` int(11) NOT NULL DEFAULT 600,
    `max_movement_update_range` int(11) unsigned NOT NULL DEFAULT 600,
    `underworld_teleport_index` int(4) NOT NULL DEFAULT 0,
    `lava_damage` int(11) DEFAULT 50,
    `min_lava_damage` int(11) NOT NULL DEFAULT 10,
    `idle_when_empty` tinyint(1) unsigned NOT NULL DEFAULT 1,
    `seconds_before_idle` int(11) unsigned NOT NULL DEFAULT 60,
    PRIMARY KEY (`id`),
    KEY `zoneidnumber` (`zoneidnumber`),
    KEY `zonename` (`short_name`)
) ENGINE = InnoDB AUTO_INCREMENT = 6047 DEFAULT CHARSET = latin1 COLLATE = latin1_swedish_ci;

CREATE TABLE
  `merchantlist` (
    `merchantid` int(11) NOT NULL DEFAULT 0,
    `slot` int(11) unsigned NOT NULL DEFAULT 0,
    `item` int(11) NOT NULL DEFAULT 0,
    `faction_required` smallint(6) NOT NULL DEFAULT -100,
    `level_required` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `min_status` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `max_status` tinyint(3) unsigned NOT NULL DEFAULT 255,
    `alt_currency_cost` smallint(5) unsigned NOT NULL DEFAULT 0,
    `classes_required` int(11) NOT NULL DEFAULT 65535,
    `probability` int(3) NOT NULL DEFAULT 100,
    `bucket_name` varchar(100) NOT NULL DEFAULT '',
    `bucket_value` varchar(100) NOT NULL DEFAULT '',
    `bucket_comparison` tinyint(3) unsigned DEFAULT 0,
    `min_expansion` tinyint(4) NOT NULL DEFAULT -1,
    `max_expansion` tinyint(4) NOT NULL DEFAULT -1,
    `content_flags` varchar(100) DEFAULT NULL,
    `content_flags_disabled` varchar(100) DEFAULT NULL,
    PRIMARY KEY (`merchantid`, `slot`),
    UNIQUE KEY `merchantid` (`merchantid`, `item`),
    KEY `item` (`item`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COLLATE = latin1_swedish_ci;

CREATE TABLE
  `spawnentry` (
    `spawngroupID` int(11) NOT NULL DEFAULT 0,
    `npcID` int(11) NOT NULL DEFAULT 0,
    `chance` smallint(4) NOT NULL DEFAULT 0,
    `condition_value_filter` mediumint(9) NOT NULL DEFAULT 1,
    `min_time` smallint(4) NOT NULL DEFAULT 0,
    `max_time` smallint(4) NOT NULL DEFAULT 0,
    `min_expansion` tinyint(4) NOT NULL DEFAULT -1,
    `max_expansion` tinyint(4) NOT NULL DEFAULT -1,
    `content_flags` varchar(100) DEFAULT NULL,
    `content_flags_disabled` varchar(100) DEFAULT NULL,
    PRIMARY KEY (`spawngroupID`, `npcID`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COLLATE = latin1_swedish_ci;

CREATE TABLE
  `spawn2` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `spawngroupID` int(11) NOT NULL DEFAULT 0,
    `zone` varchar(32) DEFAULT NULL,
    `version` smallint(5) NOT NULL DEFAULT 0,
    `x` float(14, 6) NOT NULL DEFAULT 0.000000,
    `y` float(14, 6) NOT NULL DEFAULT 0.000000,
    `z` float(14, 6) NOT NULL DEFAULT 0.000000,
    `heading` float(14, 6) NOT NULL DEFAULT 0.000000,
    `respawntime` int(11) NOT NULL DEFAULT 0,
    `variance` int(11) NOT NULL DEFAULT 0,
    `pathgrid` int(10) NOT NULL DEFAULT 0,
    `path_when_zone_idle` tinyint(1) NOT NULL DEFAULT 0,
    `_condition` mediumint(8) unsigned NOT NULL DEFAULT 0,
    `cond_value` mediumint(9) NOT NULL DEFAULT 1,
    `animation` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `min_expansion` tinyint(4) NOT NULL DEFAULT -1,
    `max_expansion` tinyint(4) NOT NULL DEFAULT -1,
    `content_flags` varchar(100) DEFAULT NULL,
    `content_flags_disabled` varchar(100) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `ZoneGroup` (`zone`),
    KEY `spawn2_spawngroupid_idx` (`spawngroupID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3266009 DEFAULT CHARSET = latin1 COLLATE = latin1_swedish_ci;

CREATE TABLE
  `spawngroup` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(200) NOT NULL DEFAULT '',
    `spawn_limit` tinyint(4) NOT NULL DEFAULT 0,
    `dist` float NOT NULL DEFAULT 0,
    `max_x` float NOT NULL DEFAULT 0,
    `min_x` float NOT NULL DEFAULT 0,
    `max_y` float NOT NULL DEFAULT 0,
    `min_y` float NOT NULL DEFAULT 0,
    `delay` int(11) NOT NULL DEFAULT 45000,
    `mindelay` int(11) NOT NULL DEFAULT 15000,
    `despawn` tinyint(3) NOT NULL DEFAULT 0,
    `despawn_timer` int(11) NOT NULL DEFAULT 100,
    `wp_spawns` tinyint(1) unsigned NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `name` (`name`)
) ENGINE = InnoDB AUTO_INCREMENT = 3288206 DEFAULT CHARSET = latin1 COLLATE = latin1_swedish_ci;

CREATE TABLE
  `npc_spells` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `name` tinytext DEFAULT NULL,
    `parent_list` int(11) unsigned NOT NULL DEFAULT 0,
    `attack_proc` smallint(5) NOT NULL DEFAULT -1,
    `proc_chance` tinyint(3) NOT NULL DEFAULT 3,
    `range_proc` smallint(5) NOT NULL DEFAULT -1,
    `rproc_chance` smallint(5) NOT NULL DEFAULT 0,
    `defensive_proc` smallint(5) NOT NULL DEFAULT -1,
    `dproc_chance` smallint(5) NOT NULL DEFAULT 0,
    `fail_recast` int(11) unsigned NOT NULL DEFAULT 0,
    `engaged_no_sp_recast_min` int(11) unsigned NOT NULL DEFAULT 0,
    `engaged_no_sp_recast_max` int(11) unsigned NOT NULL DEFAULT 0,
    `engaged_b_self_chance` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `engaged_b_other_chance` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `engaged_d_chance` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `pursue_no_sp_recast_min` int(3) unsigned NOT NULL DEFAULT 0,
    `pursue_no_sp_recast_max` int(11) unsigned NOT NULL DEFAULT 0,
    `pursue_d_chance` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `idle_no_sp_recast_min` int(11) unsigned NOT NULL DEFAULT 0,
    `idle_no_sp_recast_max` int(11) unsigned NOT NULL DEFAULT 0,
    `idle_b_chance` tinyint(11) unsigned NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 3760 DEFAULT CHARSET = latin1 COLLATE = latin1_swedish_ci;

CREATE TABLE
  `npc_spells_entries` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `npc_spells_id` int(11) NOT NULL DEFAULT 0,
    `spellid` smallint(5) unsigned NOT NULL DEFAULT 0,
    `type` int(10) unsigned NOT NULL DEFAULT 0,
    `minlevel` tinyint(3) unsigned NOT NULL DEFAULT 0,
    `maxlevel` tinyint(3) unsigned NOT NULL DEFAULT 255,
    `manacost` smallint(5) NOT NULL DEFAULT -1,
    `recast_delay` int(11) NOT NULL DEFAULT -1,
    `priority` smallint(5) NOT NULL DEFAULT 0,
    `resist_adjust` int(11) DEFAULT NULL,
    `min_hp` smallint(5) DEFAULT 0,
    `max_hp` smallint(5) DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `spellsid_spellid` (`npc_spells_id`, `spellid`)
) ENGINE = InnoDB AUTO_INCREMENT = 22252 DEFAULT CHARSET = latin1 COLLATE = latin1_swedish_ci;


CREATE TABLE
  `tradeskill_recipe` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(64) NOT NULL DEFAULT '',
    `tradeskill` smallint(6) NOT NULL DEFAULT 0,
    `skillneeded` smallint(6) NOT NULL DEFAULT 0,
    `trivial` smallint(6) NOT NULL DEFAULT 0,
    `nofail` tinyint(1) NOT NULL DEFAULT 0,
    `replace_container` tinyint(1) NOT NULL DEFAULT 0,
    `notes` tinytext DEFAULT NULL,
    `must_learn` tinyint(4) NOT NULL DEFAULT 0,
    `learned_by_item_id` int(11) NOT NULL DEFAULT 0,
    `quest` tinyint(1) NOT NULL DEFAULT 0,
    `enabled` tinyint(1) NOT NULL DEFAULT 1,
    `min_expansion` tinyint(4) NOT NULL DEFAULT -1,
    `max_expansion` tinyint(4) NOT NULL DEFAULT -1,
    `content_flags` varchar(100) DEFAULT NULL,
    `content_flags_disabled` varchar(100) DEFAULT NULL,
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 31167 DEFAULT CHARSET = latin1 COLLATE = latin1_swedish_ci;

CREATE TABLE
  `tradeskill_recipe_entries` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `recipe_id` int(11) NOT NULL DEFAULT 0,
    `item_id` int(11) NOT NULL DEFAULT 0,
    `successcount` tinyint(2) NOT NULL DEFAULT 0,
    `failcount` tinyint(2) NOT NULL DEFAULT 0,
    `componentcount` tinyint(2) NOT NULL DEFAULT 1,
    `salvagecount` tinyint(2) NOT NULL DEFAULT 0,
    `iscontainer` tinyint(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`) USING BTREE,
    KEY `recipe_id` (`recipe_id`) USING BTREE,
    KEY `item_id` (`item_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 321924 DEFAULT CHARSET = latin1 COLLATE = latin1_swedish_ci;