// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlitecachec

type Item struct {
	ItemID     int64
	Gob        string
	Expiration int64
}

type ItemRecipe struct {
	ItemID     int64
	Gob        string
	Expiration int64
}

type Npc struct {
	NpcID      int64
	Gob        string
	Expiration int64
}

type NpcFaction struct {
	FactionID  int64
	Gob        string
	Expiration int64
}

type NpcLoot struct {
	LootTableID int64
	Gob         string
	Expiration  int64
}

type NpcMerchant struct {
	NpcID      int64
	Gob        string
	Expiration int64
}

type NpcQuest struct {
	NpcID      int64
	Gob        string
	Expiration int64
}

type NpcSpawn struct {
	NpcID      int64
	Gob        string
	Expiration int64
}

type NpcSpell struct {
	NpcSpellsID int64
	Gob         string
	Expiration  int64
}

type Player struct {
	CharacterID int64
	Gob         string
	Expiration  int64
}

type Quest struct {
	QuestID    int64
	Gob        string
	Expiration int64
}
