{{ .Item.ID }}:
    {{ if (gt .Item.Classes 0) }}- "Class: {{ .Item.ClassesStr }}"{{ end }}
    {{ if (gt .Item.Races 0) }}- "Race: {{ .Item.RaceStr }}"{{ end }}
    {{ if (gt .Item.Deity 0) }}- "Deity: {{ .Item.DeityStr }}"{{ end }}
    {{ if (gt .Item.Slots 0) }}- "{{ .Item.SlotStr }}"{{ end }}
    {{ if (eq .Item.Slots 0) }}- "NONE"{{ end }}
    {{ if (gt .Item.Bagslots 0)}}- "Item Type: Container"
    - "Number of Slots: {{ .Item.Bagslots }}"
    {{ if (gt .Item.Bagtype 0) }}- "Trade Skill Container: {{ .Item.BagtypeStr }}"{{ end }}
    {{ if (gt .Item.Bagwr 0) }}- "Weight Reduction: {{ .Item.Bagwr }}%"{{ end }}
    - "This can hold {{ .Item.BagsizeStr }} and smaller items.""
    {{ end }}
    - "{{ if (ne .Item.Weight 0) }}Weight: {{ .Item.Weight }}{{ end }}"
    - "{{ if (eq .Item.Slots 0)}}{{ .Item.TypeStr }}: Inventory"
    {{else}}{{ .Item.TypeStr }}: {{ .Item.ItemTypeStr }}"
    - "{{ end }}"
    - "{{ if (gt .Item.Stackable 0)}} (stackable){{ end }}"
    - "{{ if (ne .Item.Reclevel 0) }}Rec Level: {{ .Item.Reclevel }}{{ end }}"
    - "{{ if (ne .Item.Reqlevel 0) }}Req Level: {{ .Item.Reqlevel }}{{ end }}"
    - "{{ if (ne .Item.Ac 0) }}AC: {{ .Item.Ac }}{{ end }}"
    - "{{ if (ne .Item.Hp 0) }}HP: {{ .Item.Hp }}{{ end }}"
    - "{{ if (ne .Item.Mana 0) }}Mana: {{ .Item.Mana }}{{ end }}"
    - "{{ if (ne .Item.Endur 0) }}End: {{ .Item.Endur }}{{ end }}"
    - "{{ if (ne .Item.Haste 0) }}Haste: {{ .Item.Haste }}%{{ end }}"
    - "{{ if (ne .Item.Damage 0) }}Base Damage: {{ .Item.Damage }}{{ end }}"
    - "{{ if (ne .Item.Elemdmgamt 0) }}{{ .Item.EleDamageTypeStr }} Damage: {{ .Item.Elemdmgamt }}{{ end }}"
    - "{{ if (ne .Item.Banedmgrace 0) }}Bane Damage ({{ .Item.BaneDamageTypeStr }}): {{ .Item.Banedmgamt }}{{ end }}"
    - "{{ if (ne .Item.Banedmgamt 0) }}{{ .Item.BaneDamageTypeStr }} Damage: {{ .Item.Banedmgamt }}{{ end }}"
    - "{{ if (ne .Item.Backstabdmg 0) }}Backstab Damage: {{ .Item.Backstabdmg }}{{ end }}"
    - "{{ if (ne .Item.Delay 0) }}Delay: {{ .Item.Delay }}{{ end }}"
    - "{{ if (gt .Item.DamageBonus 0)}}Damage bonus: {{ .Item.DamageBonus }}{{ end }}"
    - "{{ if (ne .Item.Range 0) }}Range: {{ .Item.Range }}{{ end }}"
    - "{{ if (ne .Item.Astr 0) }}Strength: {{ .Item.Astr }}{{ if .Item.HeroicStr }}+{{ .Item.HeroicStr }}{{ end }}{{ end }}"
    - "{{ if (ne .Item.Asta 0) }}Stamina: {{ .Item.Asta }}{{ if .Item.HeroicSta }}+{{ .Item.HeroicSta }}{{ end }}{{ end }}"
    - "{{ if (ne .Item.Aint 0) }}Intelligence: {{ .Item.Aint }}{{ if .Item.HeroicInt }}+{{ .Item.HeroicInt }}{{ end }}{{ end }}"
    - "{{ if (ne .Item.Awis 0) }}Wisdom: {{ .Item.Awis }}{{ if .Item.HeroicWis }}+{{ .Item.HeroicWis }}{{ end }}{{ end }}"
    - "{{ if (ne .Item.Aagi 0) }}Agility: {{ .Item.Aagi }}{{ if .Item.HeroicAgi }}+{{ .Item.HeroicAgi }}{{ end }}{{ end }}"
    - "{{ if (ne .Item.Adex 0) }}Dexterity: {{ .Item.Adex }}{{ if .Item.HeroicDex }}+{{ .Item.HeroicDex }}{{ end }}{{ end }}"
    - "{{ if (ne .Item.Acha 0) }}Charisma: {{ .Item.Acha }}{{ if .Item.HeroicCha }}+{{ .Item.HeroicCha }}{{ end }}{{ end }}"
    - "{{ if (ne .Item.Mr 0) }}Magic Resist: {{ .Item.Mr }}{{ if .Item.HeroicMr }}+{{ .Item.HeroicMr }}{{ end }}{{ end }}"
    - "{{ if (ne .Item.Fr 0) }}Fire Resist: {{ .Item.Fr }}{{ if .Item.HeroicFr }}+{{ .Item.HeroicFr }}{{ end }}{{ end }}"
    - "{{ if (ne .Item.Cr 0) }}Combat Effects: {{ .Item.Cr }}{{ if .Item.HeroicCr }}+{{ .Item.HeroicCr }}{{ end }}{{ end }}"
    - "{{ if (ne .Item.Dr 0) }}Disease Resist: {{ .Item.Dr }}{{ if .Item.HeroicDr }}+{{ .Item.HeroicDr }}{{ end }}{{ end }}"
    - "{{ if (ne .Item.Pr 0) }}Poison Resist: {{ .Item.Pr }}{{ if .Item.HeroicPr }}+{{ .Item.HeroicPr }}{{ end }}{{ end }}"
    - "{{ if (ne .Item.Attack 0) }}Attack: {{ .Item.Attack }}{{ end }}"
    - "{{ if (ne .Item.Regen 0) }}HP Regen: {{ .Item.Regen }}{{ end }}"
    - "{{ if (ne .Item.Manaregen 0) }}Mana Regen: {{ .Item.Manaregen }}{{ end }}"
    - "{{ if (ne .Item.Enduranceregen 0) }}Endurance Regen: {{ .Item.Enduranceregen }}{{ end }}"
    - "{{ if (ne .Item.Spellshield 0) }}Spell Shielding: {{ .Item.Spellshield }}{{ end }}"
    - "{{ if (ne .Item.Dotshielding 0) }}Dot Shielding: {{ .Item.Dotshielding }}{{ end }}"
    - "{{ if (ne .Item.Avoidance 0) }}Avoidance: {{ .Item.Avoidance }}{{ end }}"
    - "{{ if (ne .Item.Accuracy 0) }}Accuracy: {{ .Item.Accuracy }}{{ end }}"
    - "{{ if (ne .Item.Stunresist 0) }}Stun Resist: {{ .Item.Stunresist }}{{ end }}"
    - "{{ if (ne .Item.Strikethrough 0) }}Strikethrough: {{ .Item.Strikethrough }}{{ end }}"
    - "{{ if (ne .Item.Damageshield 0) }}Damage Shield: {{ .Item.Damageshield }}{{ end }}"