// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlitefilec

type ItemQuest struct {
	ItemID int64
	Gob    string
}

type ItemRecipe struct {
	ItemID int64
	Gob    string
}

type NpcQuest struct {
	NpcID int64
	Gob   string
}

type Quest struct {
	ID  int64
	Gob string
}
