CREATE TABLE authors (
  id   BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name text    NOT NULL,
  bio  text
);

CREATE TABLE `items` (
  `id` int(11) NOT NULL DEFAULT 0,
  `minstatus` smallint(5) NOT NULL DEFAULT 0,
  `Name` varchar(64) NOT NULL DEFAULT '',
  `aagi` int(11) NOT NULL DEFAULT 0,
  `ac` int(11) NOT NULL DEFAULT 0,
  `accuracy` int(11) NOT NULL DEFAULT 0,
  `acha` int(11) NOT NULL DEFAULT 0,
  `adex` int(11) NOT NULL DEFAULT 0,
  `aint` int(11) NOT NULL DEFAULT 0,
  `artifactflag` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `asta` int(11) NOT NULL DEFAULT 0,
  `astr` int(11) NOT NULL DEFAULT 0,
  `attack` int(11) NOT NULL DEFAULT 0,
  `augrestrict` int(11) NOT NULL DEFAULT 0,
  `augslot1type` tinyint(3) NOT NULL DEFAULT 0,
  `augslot1visible` tinyint(3) NOT NULL DEFAULT 0,
  `augslot2type` tinyint(3) NOT NULL DEFAULT 0,
  `augslot2visible` tinyint(3) NOT NULL DEFAULT 0,
  `augslot3type` tinyint(3) NOT NULL DEFAULT 0,
  `augslot3visible` tinyint(3) NOT NULL DEFAULT 0,
  `augslot4type` tinyint(3) NOT NULL DEFAULT 0,
  `augslot4visible` tinyint(3) NOT NULL DEFAULT 0,
  `augslot5type` tinyint(3) NOT NULL DEFAULT 0,
  `augslot5visible` tinyint(3) NOT NULL DEFAULT 0,
  `augslot6type` tinyint(3) NOT NULL DEFAULT 0,
  `augslot6visible` tinyint(3) NOT NULL DEFAULT 0,
  `augtype` int(11) NOT NULL DEFAULT 0,
  `avoidance` int(11) NOT NULL DEFAULT 0,
  `awis` int(11) NOT NULL DEFAULT 0,
  `bagsize` int(11) NOT NULL DEFAULT 0,
  `bagslots` int(11) NOT NULL DEFAULT 0,
  `bagtype` int(11) NOT NULL DEFAULT 0,
  `bagwr` int(11) NOT NULL DEFAULT 0,
  `banedmgamt` int(11) NOT NULL DEFAULT 0,
  `banedmgraceamt` int(11) NOT NULL DEFAULT 0,
  `banedmgbody` int(11) NOT NULL DEFAULT 0,
  `banedmgrace` int(11) NOT NULL DEFAULT 0,
  `bardtype` int(11) NOT NULL DEFAULT 0,
  `bardvalue` int(11) NOT NULL DEFAULT 0,
  `book` int(11) NOT NULL DEFAULT 0,
  `casttime` int(11) NOT NULL DEFAULT 0,
  `casttime_` int(11) NOT NULL DEFAULT 0,
  `charmfile` varchar(32) NOT NULL DEFAULT '',
  `charmfileid` varchar(32) NOT NULL DEFAULT '',
  `classes` int(11) NOT NULL DEFAULT 0,
  `color` int(10) unsigned NOT NULL DEFAULT 0,
  `combateffects` varchar(10) NOT NULL DEFAULT '',
  `extradmgskill` int(11) NOT NULL DEFAULT 0,
  `extradmgamt` int(11) NOT NULL DEFAULT 0,
  `price` int(11) NOT NULL DEFAULT 0,
  `cr` int(11) NOT NULL DEFAULT 0,
  `damage` int(11) NOT NULL DEFAULT 0,
  `damageshield` int(11) NOT NULL DEFAULT 0,
  `deity` int(11) NOT NULL DEFAULT 0,
  `delay` int(11) NOT NULL DEFAULT 0,
  `augdistiller` int(11) unsigned NOT NULL DEFAULT 0,
  `dotshielding` int(11) NOT NULL DEFAULT 0,
  `dr` int(11) NOT NULL DEFAULT 0,
  `clicktype` int(11) NOT NULL DEFAULT 0,
  `clicklevel2` int(11) NOT NULL DEFAULT 0,
  `elemdmgtype` int(11) NOT NULL DEFAULT 0,
  `elemdmgamt` int(11) NOT NULL DEFAULT 0,
  `endur` int(11) NOT NULL DEFAULT 0,
  `factionamt1` int(11) NOT NULL DEFAULT 0,
  `factionamt2` int(11) NOT NULL DEFAULT 0,
  `factionamt3` int(11) NOT NULL DEFAULT 0,
  `factionamt4` int(11) NOT NULL DEFAULT 0,
  `factionmod1` int(11) NOT NULL DEFAULT 0,
  `factionmod2` int(11) NOT NULL DEFAULT 0,
  `factionmod3` int(11) NOT NULL DEFAULT 0,
  `factionmod4` int(11) NOT NULL DEFAULT 0,
  `filename` varchar(32) NOT NULL DEFAULT '',
  `focuseffect` int(11) NOT NULL DEFAULT 0,
  `fr` int(11) NOT NULL DEFAULT 0,
  `fvnodrop` int(11) NOT NULL DEFAULT 0,
  `haste` int(11) NOT NULL DEFAULT 0,
  `clicklevel` int(11) NOT NULL DEFAULT 0,
  `hp` int(11) NOT NULL DEFAULT 0,
  `regen` int(11) NOT NULL DEFAULT 0,
  `icon` int(11) NOT NULL DEFAULT 0,
  `idfile` varchar(30) NOT NULL DEFAULT '',
  `itemclass` int(11) NOT NULL DEFAULT 0,
  `itemtype` int(11) NOT NULL DEFAULT 0,
  `ldonprice` int(11) NOT NULL DEFAULT 0,
  `ldontheme` int(11) NOT NULL DEFAULT 0,
  `ldonsold` int(11) NOT NULL DEFAULT 0,
  `light` int(11) NOT NULL DEFAULT 0,
  `lore` varchar(80) NOT NULL DEFAULT '',
  `loregroup` int(11) NOT NULL DEFAULT 0,
  `magic` int(11) NOT NULL DEFAULT 0,
  `mana` int(11) NOT NULL DEFAULT 0,
  `manaregen` int(11) NOT NULL DEFAULT 0,
  `enduranceregen` int(11) NOT NULL DEFAULT 0,
  `material` int(11) NOT NULL DEFAULT 0,
  `herosforgemodel` int(11) NOT NULL DEFAULT 0,
  `maxcharges` int(11) NOT NULL DEFAULT 0,
  `mr` int(11) NOT NULL DEFAULT 0,
  `nodrop` int(11) NOT NULL DEFAULT 0,
  `norent` int(11) NOT NULL DEFAULT 0,
  `pendingloreflag` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `pr` int(11) NOT NULL DEFAULT 0,
  `procrate` int(11) NOT NULL DEFAULT 0,
  `races` int(11) NOT NULL DEFAULT 0,
  `range` int(11) NOT NULL DEFAULT 0,
  `reclevel` int(11) NOT NULL DEFAULT 0,
  `recskill` int(11) NOT NULL DEFAULT 0,
  `reqlevel` int(11) NOT NULL DEFAULT 0,
  `sellrate` float NOT NULL DEFAULT 0,
  `shielding` int(11) NOT NULL DEFAULT 0,
  `size` int(11) NOT NULL DEFAULT 0,
  `skillmodtype` int(11) NOT NULL DEFAULT 0,
  `skillmodvalue` int(11) NOT NULL DEFAULT 0,
  `slots` int(11) NOT NULL DEFAULT 0,
  `clickeffect` int(11) NOT NULL DEFAULT 0,
  `spellshield` int(11) NOT NULL DEFAULT 0,
  `strikethrough` int(11) NOT NULL DEFAULT 0,
  `stunresist` int(11) NOT NULL DEFAULT 0,
  `summonedflag` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `tradeskills` int(11) NOT NULL DEFAULT 0,
  `favor` int(11) NOT NULL DEFAULT 0,
  `weight` int(11) NOT NULL DEFAULT 0,
  `UNK012` int(11) NOT NULL DEFAULT 0,
  `UNK013` int(11) NOT NULL DEFAULT 0,
  `benefitflag` int(11) NOT NULL DEFAULT 0,
  `UNK054` int(11) NOT NULL DEFAULT 0,
  `UNK059` int(11) NOT NULL DEFAULT 0,
  `booktype` int(11) NOT NULL DEFAULT 0,
  `recastdelay` int(11) NOT NULL DEFAULT 0,
  `recasttype` int(11) NOT NULL DEFAULT 0,
  `guildfavor` int(11) NOT NULL DEFAULT 0,
  `UNK123` int(11) NOT NULL DEFAULT 0,
  `UNK124` int(11) NOT NULL DEFAULT 0,
  `attuneable` int(11) NOT NULL DEFAULT 0,
  `nopet` int(11) NOT NULL DEFAULT 0,
  `updated` datetime DEFAULT NULL,
  `comment` varchar(255) NOT NULL DEFAULT '',
  `UNK127` int(11) NOT NULL DEFAULT 0,
  `pointtype` int(11) NOT NULL DEFAULT 0,
  `potionbelt` int(11) NOT NULL DEFAULT 0,
  `potionbeltslots` int(11) NOT NULL DEFAULT 0,
  `stacksize` int(11) NOT NULL DEFAULT 0,
  `notransfer` int(11) NOT NULL DEFAULT 0,
  `stackable` int(11) NOT NULL DEFAULT 0,
  `UNK134` varchar(255) NOT NULL DEFAULT '',
  `UNK137` int(11) NOT NULL DEFAULT 0,
  `proceffect` int(11) NOT NULL DEFAULT 0,
  `proctype` int(11) NOT NULL DEFAULT 0,
  `proclevel2` int(11) NOT NULL DEFAULT 0,
  `proclevel` int(11) NOT NULL DEFAULT 0,
  `UNK142` int(11) NOT NULL DEFAULT 0,
  `worneffect` int(11) NOT NULL DEFAULT 0,
  `worntype` int(11) NOT NULL DEFAULT 0,
  `wornlevel2` int(11) NOT NULL DEFAULT 0,
  `wornlevel` int(11) NOT NULL DEFAULT 0,
  `UNK147` int(11) NOT NULL DEFAULT 0,
  `focustype` int(11) NOT NULL DEFAULT 0,
  `focuslevel2` int(11) NOT NULL DEFAULT 0,
  `focuslevel` int(11) NOT NULL DEFAULT 0,
  `UNK152` int(11) NOT NULL DEFAULT 0,
  `scrolleffect` int(11) NOT NULL DEFAULT 0,
  `scrolltype` int(11) NOT NULL DEFAULT 0,
  `scrolllevel2` int(11) NOT NULL DEFAULT 0,
  `scrolllevel` int(11) NOT NULL DEFAULT 0,
  `UNK157` int(11) NOT NULL DEFAULT 0,
  `serialized` datetime DEFAULT NULL,
  `verified` datetime DEFAULT NULL,
  `serialization` text DEFAULT NULL,
  `source` varchar(20) NOT NULL DEFAULT '',
  `UNK033` int(11) NOT NULL DEFAULT 0,
  `lorefile` varchar(32) NOT NULL DEFAULT '',
  `UNK014` int(11) NOT NULL DEFAULT 0,
  `svcorruption` int(11) NOT NULL DEFAULT 0,
  `skillmodmax` int(11) NOT NULL DEFAULT 0,
  `UNK060` int(11) NOT NULL DEFAULT 0,
  `augslot1unk2` int(11) NOT NULL DEFAULT 0,
  `augslot2unk2` int(11) NOT NULL DEFAULT 0,
  `augslot3unk2` int(11) NOT NULL DEFAULT 0,
  `augslot4unk2` int(11) NOT NULL DEFAULT 0,
  `augslot5unk2` int(11) NOT NULL DEFAULT 0,
  `augslot6unk2` int(11) NOT NULL DEFAULT 0,
  `UNK120` int(11) NOT NULL DEFAULT 0,
  `UNK121` int(11) NOT NULL DEFAULT 0,
  `questitemflag` int(11) NOT NULL DEFAULT 0,
  `UNK132` text CHARACTER SET utf8 DEFAULT NULL,
  `clickunk5` int(11) NOT NULL DEFAULT 0,
  `clickunk6` varchar(32) NOT NULL DEFAULT '',
  `clickunk7` int(11) NOT NULL DEFAULT 0,
  `procunk1` int(11) NOT NULL DEFAULT 0,
  `procunk2` int(11) NOT NULL DEFAULT 0,
  `procunk3` int(11) NOT NULL DEFAULT 0,
  `procunk4` int(11) NOT NULL DEFAULT 0,
  `procunk6` varchar(32) NOT NULL DEFAULT '',
  `procunk7` int(11) NOT NULL DEFAULT 0,
  `wornunk1` int(11) NOT NULL DEFAULT 0,
  `wornunk2` int(11) NOT NULL DEFAULT 0,
  `wornunk3` int(11) NOT NULL DEFAULT 0,
  `wornunk4` int(11) NOT NULL DEFAULT 0,
  `wornunk5` int(11) NOT NULL DEFAULT 0,
  `wornunk6` varchar(32) NOT NULL DEFAULT '',
  `wornunk7` int(11) NOT NULL DEFAULT 0,
  `focusunk1` int(11) NOT NULL DEFAULT 0,
  `focusunk2` int(11) NOT NULL DEFAULT 0,
  `focusunk3` int(11) NOT NULL DEFAULT 0,
  `focusunk4` int(11) NOT NULL DEFAULT 0,
  `focusunk5` int(11) NOT NULL DEFAULT 0,
  `focusunk6` varchar(32) NOT NULL DEFAULT '',
  `focusunk7` int(11) NOT NULL DEFAULT 0,
  `scrollunk1` int(11) unsigned NOT NULL DEFAULT 0,
  `scrollunk2` int(11) NOT NULL DEFAULT 0,
  `scrollunk3` int(11) NOT NULL DEFAULT 0,
  `scrollunk4` int(11) NOT NULL DEFAULT 0,
  `scrollunk5` int(11) NOT NULL DEFAULT 0,
  `scrollunk6` varchar(32) NOT NULL DEFAULT '',
  `scrollunk7` int(11) NOT NULL DEFAULT 0,
  `UNK193` int(11) NOT NULL DEFAULT 0,
  `purity` int(11) NOT NULL DEFAULT 0,
  `evoitem` int(11) NOT NULL DEFAULT 0,
  `evoid` int(11) NOT NULL DEFAULT 0,
  `evolvinglevel` int(11) NOT NULL DEFAULT 0,
  `evomax` int(11) NOT NULL DEFAULT 0,
  `clickname` varchar(64) NOT NULL DEFAULT '',
  `procname` varchar(64) NOT NULL DEFAULT '',
  `wornname` varchar(64) NOT NULL DEFAULT '',
  `focusname` varchar(64) NOT NULL DEFAULT '',
  `scrollname` varchar(64) NOT NULL DEFAULT '',
  `dsmitigation` smallint(6) NOT NULL DEFAULT 0,
  `heroic_str` smallint(6) NOT NULL DEFAULT 0,
  `heroic_int` smallint(6) NOT NULL DEFAULT 0,
  `heroic_wis` smallint(6) NOT NULL DEFAULT 0,
  `heroic_agi` smallint(6) NOT NULL DEFAULT 0,
  `heroic_dex` smallint(6) NOT NULL DEFAULT 0,
  `heroic_sta` smallint(6) NOT NULL DEFAULT 0,
  `heroic_cha` smallint(6) NOT NULL DEFAULT 0,
  `heroic_pr` smallint(6) NOT NULL DEFAULT 0,
  `heroic_dr` smallint(6) NOT NULL DEFAULT 0,
  `heroic_fr` smallint(6) NOT NULL DEFAULT 0,
  `heroic_cr` smallint(6) NOT NULL DEFAULT 0,
  `heroic_mr` smallint(6) NOT NULL DEFAULT 0,
  `heroic_svcorrup` smallint(6) NOT NULL DEFAULT 0,
  `healamt` smallint(6) NOT NULL DEFAULT 0,
  `spelldmg` smallint(6) NOT NULL DEFAULT 0,
  `clairvoyance` smallint(6) NOT NULL DEFAULT 0,
  `backstabdmg` smallint(6) NOT NULL DEFAULT 0,
  `created` varchar(64) NOT NULL DEFAULT '',
  `elitematerial` smallint(6) NOT NULL DEFAULT 0,
  `ldonsellbackrate` smallint(6) NOT NULL DEFAULT 0,
  `scriptfileid` mediumint(6) NOT NULL DEFAULT 0,
  `expendablearrow` smallint(6) NOT NULL DEFAULT 0,
  `powersourcecapacity` mediumint(7) NOT NULL DEFAULT 0,
  `bardeffect` mediumint(6) NOT NULL DEFAULT 0,
  `bardeffecttype` smallint(6) NOT NULL DEFAULT 0,
  `bardlevel2` smallint(6) NOT NULL DEFAULT 0,
  `bardlevel` smallint(6) NOT NULL DEFAULT 0,
  `bardunk1` smallint(6) NOT NULL DEFAULT 0,
  `bardunk2` smallint(6) NOT NULL DEFAULT 0,
  `bardunk3` smallint(6) NOT NULL DEFAULT 0,
  `bardunk4` smallint(6) NOT NULL DEFAULT 0,
  `bardunk5` smallint(6) NOT NULL DEFAULT 0,
  `bardname` varchar(64) NOT NULL DEFAULT '',
  `bardunk7` smallint(6) NOT NULL DEFAULT 0,
  `UNK214` smallint(6) NOT NULL DEFAULT 0,
  `subtype` int(11) NOT NULL DEFAULT 0,
  `UNK220` int(11) NOT NULL DEFAULT 0,
  `UNK221` int(11) NOT NULL DEFAULT 0,
  `heirloom` int(11) NOT NULL DEFAULT 0,
  `UNK223` int(11) NOT NULL DEFAULT 0,
  `UNK224` int(11) NOT NULL DEFAULT 0,
  `UNK225` int(11) NOT NULL DEFAULT 0,
  `UNK226` int(11) NOT NULL DEFAULT 0,
  `UNK227` int(11) NOT NULL DEFAULT 0,
  `UNK228` int(11) NOT NULL DEFAULT 0,
  `UNK229` int(11) NOT NULL DEFAULT 0,
  `UNK230` int(11) NOT NULL DEFAULT 0,
  `UNK231` int(11) NOT NULL DEFAULT 0,
  `UNK232` int(11) NOT NULL DEFAULT 0,
  `UNK233` int(11) NOT NULL DEFAULT 0,
  `UNK234` int(11) NOT NULL DEFAULT 0,
  `placeable` int(11) NOT NULL DEFAULT 0,
  `UNK236` int(11) NOT NULL DEFAULT 0,
  `UNK237` int(11) NOT NULL DEFAULT 0,
  `UNK238` int(11) NOT NULL DEFAULT 0,
  `UNK239` int(11) NOT NULL DEFAULT 0,
  `UNK240` int(11) NOT NULL DEFAULT 0,
  `UNK241` int(11) NOT NULL DEFAULT 0,
  `epicitem` int(11) NOT NULL DEFAULT 0,
  UNIQUE KEY `ID` (`id`),
  KEY `name_idx` (`Name`),
  KEY `lore_idx` (`lore`),
  KEY `minstatus` (`minstatus`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

CREATE TABLE `npc_types` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` text NOT NULL,
  `lastname` varchar(32) DEFAULT NULL,
  `level` tinyint(2) unsigned NOT NULL DEFAULT 0,
  `race` smallint(5) unsigned NOT NULL DEFAULT 0,
  `class` tinyint(2) unsigned NOT NULL DEFAULT 0,
  `bodytype` int(11) NOT NULL DEFAULT 1,
  `hp` bigint(20) NOT NULL DEFAULT 0,
  `mana` bigint(20) NOT NULL DEFAULT 0,
  `gender` tinyint(2) unsigned NOT NULL DEFAULT 0,
  `texture` tinyint(2) unsigned NOT NULL DEFAULT 0,
  `helmtexture` tinyint(2) unsigned NOT NULL DEFAULT 0,
  `herosforgemodel` int(11) NOT NULL DEFAULT 0,
  `size` float NOT NULL DEFAULT 0,
  `hp_regen_rate` bigint(20) NOT NULL DEFAULT 0,
  `hp_regen_per_second` bigint(20) NOT NULL DEFAULT 0,
  `mana_regen_rate` bigint(20) NOT NULL DEFAULT 0,
  `loottable_id` int(11) unsigned NOT NULL DEFAULT 0,
  `merchant_id` int(11) unsigned NOT NULL DEFAULT 0,
  `alt_currency_id` int(11) unsigned NOT NULL DEFAULT 0,
  `npc_spells_id` int(11) unsigned NOT NULL DEFAULT 0,
  `npc_spells_effects_id` int(11) unsigned NOT NULL DEFAULT 0,
  `npc_faction_id` int(11) NOT NULL DEFAULT 0,
  `adventure_template_id` int(10) unsigned NOT NULL DEFAULT 0,
  `trap_template` int(10) unsigned DEFAULT 0,
  `mindmg` int(10) unsigned NOT NULL DEFAULT 0,
  `maxdmg` int(10) unsigned NOT NULL DEFAULT 0,
  `attack_count` smallint(6) NOT NULL DEFAULT -1,
  `npcspecialattks` varchar(36) NOT NULL DEFAULT '',
  `special_abilities` text DEFAULT NULL,
  `aggroradius` int(10) unsigned NOT NULL DEFAULT 0,
  `assistradius` int(10) unsigned NOT NULL DEFAULT 0,
  `face` int(10) unsigned NOT NULL DEFAULT 1,
  `luclin_hairstyle` int(10) unsigned NOT NULL DEFAULT 1,
  `luclin_haircolor` int(10) unsigned NOT NULL DEFAULT 1,
  `luclin_eyecolor` int(10) unsigned NOT NULL DEFAULT 1,
  `luclin_eyecolor2` int(10) unsigned NOT NULL DEFAULT 1,
  `luclin_beardcolor` int(10) unsigned NOT NULL DEFAULT 1,
  `luclin_beard` int(10) unsigned NOT NULL DEFAULT 0,
  `drakkin_heritage` int(10) NOT NULL DEFAULT 0,
  `drakkin_tattoo` int(10) NOT NULL DEFAULT 0,
  `drakkin_details` int(10) NOT NULL DEFAULT 0,
  `armortint_id` int(10) unsigned NOT NULL DEFAULT 0,
  `armortint_red` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `armortint_green` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `armortint_blue` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `d_melee_texture1` int(11) unsigned NOT NULL DEFAULT 0,
  `d_melee_texture2` int(11) unsigned NOT NULL DEFAULT 0,
  `ammo_idfile` varchar(30) NOT NULL DEFAULT 'IT10',
  `prim_melee_type` tinyint(4) unsigned NOT NULL DEFAULT 28,
  `sec_melee_type` tinyint(4) unsigned NOT NULL DEFAULT 28,
  `ranged_type` tinyint(4) unsigned NOT NULL DEFAULT 7,
  `runspeed` float NOT NULL DEFAULT 0,
  `MR` smallint(5) NOT NULL DEFAULT 0,
  `CR` smallint(5) NOT NULL DEFAULT 0,
  `DR` smallint(5) NOT NULL DEFAULT 0,
  `FR` smallint(5) NOT NULL DEFAULT 0,
  `PR` smallint(5) NOT NULL DEFAULT 0,
  `Corrup` smallint(5) NOT NULL DEFAULT 0,
  `PhR` smallint(5) unsigned NOT NULL DEFAULT 0,
  `see_invis` smallint(4) NOT NULL DEFAULT 0,
  `see_invis_undead` smallint(4) NOT NULL DEFAULT 0,
  `qglobal` int(2) unsigned NOT NULL DEFAULT 0,
  `AC` smallint(5) NOT NULL DEFAULT 0,
  `npc_aggro` tinyint(4) NOT NULL DEFAULT 0,
  `spawn_limit` tinyint(4) NOT NULL DEFAULT 0,
  `attack_speed` float NOT NULL DEFAULT 0,
  `attack_delay` tinyint(3) unsigned NOT NULL DEFAULT 30,
  `findable` tinyint(4) NOT NULL DEFAULT 0,
  `STR` mediumint(8) unsigned NOT NULL DEFAULT 75,
  `STA` mediumint(8) unsigned NOT NULL DEFAULT 75,
  `DEX` mediumint(8) unsigned NOT NULL DEFAULT 75,
  `AGI` mediumint(8) unsigned NOT NULL DEFAULT 75,
  `_INT` mediumint(8) unsigned NOT NULL DEFAULT 80,
  `WIS` mediumint(8) unsigned NOT NULL DEFAULT 75,
  `CHA` mediumint(8) unsigned NOT NULL DEFAULT 75,
  `see_hide` tinyint(4) NOT NULL DEFAULT 0,
  `see_improved_hide` tinyint(4) NOT NULL DEFAULT 0,
  `trackable` tinyint(4) NOT NULL DEFAULT 1,
  `isbot` tinyint(4) NOT NULL DEFAULT 0,
  `exclude` tinyint(4) NOT NULL DEFAULT 1,
  `ATK` mediumint(9) NOT NULL DEFAULT 0,
  `Accuracy` mediumint(9) NOT NULL DEFAULT 0,
  `Avoidance` mediumint(9) unsigned NOT NULL DEFAULT 0,
  `slow_mitigation` smallint(4) NOT NULL DEFAULT 0,
  `version` smallint(5) unsigned NOT NULL DEFAULT 0,
  `maxlevel` tinyint(3) NOT NULL DEFAULT 0,
  `scalerate` int(11) NOT NULL DEFAULT 100,
  `private_corpse` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `unique_spawn_by_name` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `underwater` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `isquest` tinyint(3) NOT NULL DEFAULT 0,
  `emoteid` int(10) unsigned NOT NULL DEFAULT 0,
  `spellscale` float NOT NULL DEFAULT 100,
  `healscale` float NOT NULL DEFAULT 100,
  `no_target_hotkey` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `raid_target` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `armtexture` tinyint(2) NOT NULL DEFAULT 0,
  `bracertexture` tinyint(2) NOT NULL DEFAULT 0,
  `handtexture` tinyint(2) NOT NULL DEFAULT 0,
  `legtexture` tinyint(2) NOT NULL DEFAULT 0,
  `feettexture` tinyint(2) NOT NULL DEFAULT 0,
  `light` tinyint(2) NOT NULL DEFAULT 0,
  `walkspeed` tinyint(2) NOT NULL DEFAULT 0,
  `peqid` int(11) NOT NULL DEFAULT 0,
  `unique_` tinyint(2) NOT NULL DEFAULT 0,
  `fixed` tinyint(2) NOT NULL DEFAULT 0,
  `ignore_despawn` tinyint(2) NOT NULL DEFAULT 0,
  `show_name` tinyint(2) NOT NULL DEFAULT 1,
  `untargetable` tinyint(2) NOT NULL DEFAULT 0,
  `charm_ac` smallint(5) DEFAULT 0,
  `charm_min_dmg` int(10) DEFAULT 0,
  `charm_max_dmg` int(10) DEFAULT 0,
  `charm_attack_delay` tinyint(3) DEFAULT 0,
  `charm_accuracy_rating` mediumint(9) DEFAULT 0,
  `charm_avoidance_rating` mediumint(9) DEFAULT 0,
  `charm_atk` mediumint(9) DEFAULT 0,
  `skip_global_loot` tinyint(4) DEFAULT 0,
  `rare_spawn` tinyint(4) DEFAULT 0,
  `stuck_behavior` tinyint(4) NOT NULL DEFAULT 0,
  `model` smallint(5) NOT NULL DEFAULT 0,
  `flymode` tinyint(4) NOT NULL DEFAULT -1,
  `always_aggro` tinyint(1) NOT NULL DEFAULT 0,
  `exp_mod` int(11) NOT NULL DEFAULT 100,
  `heroic_strikethrough` int(11) NOT NULL DEFAULT 0,
  `faction_amount` int(10) NOT NULL DEFAULT 0,
  `keeps_sold_items` tinyint(1) unsigned NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2000911 DEFAULT CHARSET=latin1 PACK_KEYS=0;
/*!40101 SET character_set_client = @saved_cs_client */;

CREATE TABLE `character_data` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL DEFAULT 0,
  `name` varchar(64) NOT NULL DEFAULT '',
  `last_name` varchar(64) NOT NULL DEFAULT '',
  `title` varchar(32) NOT NULL DEFAULT '',
  `suffix` varchar(32) NOT NULL DEFAULT '',
  `zone_id` int(11) unsigned NOT NULL DEFAULT 0,
  `zone_instance` int(11) unsigned NOT NULL DEFAULT 0,
  `y` float NOT NULL DEFAULT 0,
  `x` float NOT NULL DEFAULT 0,
  `z` float NOT NULL DEFAULT 0,
  `heading` float NOT NULL DEFAULT 0,
  `gender` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `race` smallint(11) unsigned NOT NULL DEFAULT 0,
  `class` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `level` int(11) unsigned NOT NULL DEFAULT 0,
  `deity` int(11) unsigned NOT NULL DEFAULT 0,
  `birthday` int(11) unsigned NOT NULL DEFAULT 0,
  `last_login` int(11) unsigned NOT NULL DEFAULT 0,
  `time_played` int(11) unsigned NOT NULL DEFAULT 0,
  `level2` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `anon` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `gm` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `face` int(11) unsigned NOT NULL DEFAULT 0,
  `hair_color` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `hair_style` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `beard` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `beard_color` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `eye_color_1` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `eye_color_2` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `drakkin_heritage` int(11) unsigned NOT NULL DEFAULT 0,
  `drakkin_tattoo` int(11) unsigned NOT NULL DEFAULT 0,
  `drakkin_details` int(11) unsigned NOT NULL DEFAULT 0,
  `ability_time_seconds` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `ability_number` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `ability_time_minutes` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `ability_time_hours` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `exp` int(11) unsigned NOT NULL DEFAULT 0,
  `exp_enabled` tinyint(1) unsigned NOT NULL DEFAULT 1,
  `aa_points_spent` int(11) unsigned NOT NULL DEFAULT 0,
  `aa_exp` int(11) unsigned NOT NULL DEFAULT 0,
  `aa_points` int(11) unsigned NOT NULL DEFAULT 0,
  `group_leadership_exp` int(11) unsigned NOT NULL DEFAULT 0,
  `raid_leadership_exp` int(11) unsigned NOT NULL DEFAULT 0,
  `group_leadership_points` int(11) unsigned NOT NULL DEFAULT 0,
  `raid_leadership_points` int(11) unsigned NOT NULL DEFAULT 0,
  `points` int(11) unsigned NOT NULL DEFAULT 0,
  `cur_hp` int(11) unsigned NOT NULL DEFAULT 0,
  `mana` int(11) unsigned NOT NULL DEFAULT 0,
  `endurance` int(11) unsigned NOT NULL DEFAULT 0,
  `intoxication` int(11) unsigned NOT NULL DEFAULT 0,
  `str` int(11) unsigned NOT NULL DEFAULT 0,
  `sta` int(11) unsigned NOT NULL DEFAULT 0,
  `cha` int(11) unsigned NOT NULL DEFAULT 0,
  `dex` int(11) unsigned NOT NULL DEFAULT 0,
  `int` int(11) unsigned NOT NULL DEFAULT 0,
  `agi` int(11) unsigned NOT NULL DEFAULT 0,
  `wis` int(11) unsigned NOT NULL DEFAULT 0,
  `zone_change_count` int(11) unsigned NOT NULL DEFAULT 0,
  `toxicity` int(11) unsigned NOT NULL DEFAULT 0,
  `hunger_level` int(11) unsigned NOT NULL DEFAULT 0,
  `thirst_level` int(11) unsigned NOT NULL DEFAULT 0,
  `ability_up` int(11) unsigned NOT NULL DEFAULT 0,
  `ldon_points_guk` int(11) unsigned NOT NULL DEFAULT 0,
  `ldon_points_mir` int(11) unsigned NOT NULL DEFAULT 0,
  `ldon_points_mmc` int(11) unsigned NOT NULL DEFAULT 0,
  `ldon_points_ruj` int(11) unsigned NOT NULL DEFAULT 0,
  `ldon_points_tak` int(11) unsigned NOT NULL DEFAULT 0,
  `ldon_points_available` int(11) unsigned NOT NULL DEFAULT 0,
  `tribute_time_remaining` int(11) unsigned NOT NULL DEFAULT 0,
  `career_tribute_points` int(11) unsigned NOT NULL DEFAULT 0,
  `tribute_points` int(11) unsigned NOT NULL DEFAULT 0,
  `tribute_active` int(11) unsigned NOT NULL DEFAULT 0,
  `pvp_status` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `pvp_kills` int(11) unsigned NOT NULL DEFAULT 0,
  `pvp_deaths` int(11) unsigned NOT NULL DEFAULT 0,
  `pvp_current_points` int(11) unsigned NOT NULL DEFAULT 0,
  `pvp_career_points` int(11) unsigned NOT NULL DEFAULT 0,
  `pvp_best_kill_streak` int(11) unsigned NOT NULL DEFAULT 0,
  `pvp_worst_death_streak` int(11) unsigned NOT NULL DEFAULT 0,
  `pvp_current_kill_streak` int(11) unsigned NOT NULL DEFAULT 0,
  `pvp2` int(11) unsigned NOT NULL DEFAULT 0,
  `pvp_type` int(11) unsigned NOT NULL DEFAULT 0,
  `show_helm` int(11) unsigned NOT NULL DEFAULT 0,
  `group_auto_consent` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `raid_auto_consent` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `guild_auto_consent` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `leadership_exp_on` tinyint(11) unsigned NOT NULL DEFAULT 0,
  `RestTimer` int(11) unsigned NOT NULL DEFAULT 0,
  `air_remaining` int(11) unsigned NOT NULL DEFAULT 0,
  `autosplit_enabled` int(11) unsigned NOT NULL DEFAULT 0,
  `lfp` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `lfg` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `mailkey` char(16) NOT NULL DEFAULT '',
  `xtargets` tinyint(3) unsigned NOT NULL DEFAULT 5,
  `firstlogon` tinyint(3) NOT NULL DEFAULT 0,
  `e_aa_effects` int(11) unsigned NOT NULL DEFAULT 0,
  `e_percent_to_aa` int(11) unsigned NOT NULL DEFAULT 0,
  `e_expended_aa_spent` int(11) unsigned NOT NULL DEFAULT 0,
  `aa_points_spent_old` int(11) unsigned NOT NULL DEFAULT 0,
  `aa_points_old` int(11) unsigned NOT NULL DEFAULT 0,
  `e_last_invsnapshot` int(11) unsigned NOT NULL DEFAULT 0,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `account_id` (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
