package models

import "github.com/xackery/tinywebeq/db/mysql/storage/mysqlc"

func (m *Spell) DecodeSpellsNew(in mysqlc.SpellsNew) {
	m.ID = in.ID
	m.Name = in.Name.String
	m.Player1 = in.Player1.String
	m.TeleportZone = in.TeleportZone.String
	m.YouCast = in.YouCast.String
	m.OtherCasts = in.OtherCasts.String
	m.CastOnYou = in.CastOnYou.String
	m.CastOnOther = in.CastOnOther.String
	m.SpellFades = in.SpellFades.String
	m.Range = in.Range
	m.Aoerange = in.Aoerange
	m.Pushback = in.Pushback
	m.Pushup = in.Pushup
	m.CastTime = in.CastTime
	m.RecoveryTime = in.RecoveryTime
	m.RecastTime = in.RecastTime
	m.DurationCalc = in.Buffdurationformula
	m.DurationCap = in.Buffduration
	m.Aeduration = in.Aeduration
	m.Mana = in.Mana
	m.Bases = []int32{in.EffectBaseValue1, in.EffectBaseValue2, in.EffectBaseValue3, in.EffectBaseValue4, in.EffectBaseValue5, in.EffectBaseValue6, in.EffectBaseValue7, in.EffectBaseValue8, in.EffectBaseValue9, in.EffectBaseValue10, in.EffectBaseValue11, in.EffectBaseValue12}
	m.Limits = []int32{in.EffectLimitValue1, in.EffectLimitValue2, in.EffectLimitValue3, in.EffectLimitValue4, in.EffectLimitValue5, in.EffectLimitValue6, in.EffectLimitValue7, in.EffectLimitValue8, in.EffectLimitValue9, in.EffectLimitValue10, in.EffectLimitValue11, in.EffectLimitValue12}
	m.Maxes = []int32{in.Max1, in.Max2, in.Max3, in.Max4, in.Max5, in.Max6, in.Max7, in.Max8, in.Max9, in.Max10, in.Max11, in.Max12}
	m.Icon = in.Icon
	m.Memicon = in.Memicon
	m.Components = []int32{in.Components1, in.Components2, in.Components3, in.Components4}
	m.ComponentCounts = []int32{in.ComponentCounts1, in.ComponentCounts2, in.ComponentCounts3, in.ComponentCounts4}
	m.NoExpendReagents = []int32{in.Noexpendreagent1, in.Noexpendreagent2, in.Noexpendreagent3, in.Noexpendreagent4}
	m.Calcs = []int32{in.Formula1, in.Formula2, in.Formula3, in.Formula4, in.Formula5, in.Formula6, in.Formula7, in.Formula8, in.Formula9, in.Formula10, in.Formula11, in.Formula12}

	m.Lighttype = in.Lighttype
	m.Goodeffect = in.Goodeffect
	m.Activated = in.Activated
	m.Resisttype = in.Resisttype
	m.Attribs = []int32{in.Effectid1, in.Effectid2, in.Effectid3, in.Effectid4, in.Effectid5, in.Effectid6, in.Effectid7, in.Effectid8, in.Effectid9, in.Effectid10, in.Effectid11, in.Effectid12}
	m.TargetType = in.Targettype
	m.Basediff = in.Basediff
	m.Skill = in.Skill
	m.Zonetype = in.Zonetype
	m.Environmenttype = in.Environmenttype
	m.Timeofday = in.Timeofday
	m.Classes = []int32{in.Classes1, in.Classes2, in.Classes3, in.Classes4, in.Classes5, in.Classes6, in.Classes7, in.Classes8, in.Classes9, in.Classes10, in.Classes11, in.Classes12, in.Classes13, in.Classes14, in.Classes15, in.Classes16}
	m.Castinganim = in.Castinganim
	m.Targetanim = in.Targetanim
	m.Traveltype = in.Traveltype
	m.Spellaffectindex = in.Spellaffectindex
	m.DisallowSit = in.DisallowSit
	m.Deities = []int32{in.Deities0, in.Deities1, in.Deities2, in.Deities3, in.Deities4, in.Deities5, in.Deities6, in.Deities7, in.Deities8, in.Deities9, in.Deities10, in.Deities11, in.Deities12, in.Deities13, in.Deities14, in.Deities15, in.Deities16}
	m.Field142 = in.Field142
	m.Field143 = in.Field143
	m.NewIcon = in.NewIcon
	m.Spellanim = in.Spellanim
	m.Uninterruptable = in.Uninterruptable
	m.Resistdiff = in.Resistdiff
	m.DotStackingExempt = in.DotStackingExempt
	m.Deleteable = in.Deleteable
	m.Recourselink = in.Recourselink
	m.NoPartialResist = in.NoPartialResist
	m.Field152 = in.Field152
	m.Field153 = in.Field153
	m.ShortBuffBox = in.ShortBuffBox
	m.Descnum = in.Descnum
	m.Typedescnum = in.Typedescnum.Int32
	m.Effectdescnum = in.Effectdescnum.Int32
	m.Effectdescnum2 = in.Effectdescnum2
	m.NpcNoLos = in.NpcNoLos
	m.Field160 = in.Field160
	m.Reflectable = in.Reflectable
	m.Bonushate = in.Bonushate
	m.Field163 = in.Field163
	// m.Field164 = in.Field164
	// m.LdonTrap = in.LdonTrap
	// m.Endurcost = in.Endurcost
	// m.Endurtimerindex = in.Endurtimerindex
	// m.Isdiscipline = in.Isdiscipline
	// m.Field169 = in.Field169
	// m.Field170 = in.Field170
	// m.Field171 = in.Field171
	// m.Field172 = in.Field172
	// m.Hateadded = in.Hateadded
	// m.Endurupkeep = in.Endurupkeep
	// m.Numhitstype = in.Numhitstype
	// m.Numhits = in.Numhits
	// m.Pvpresistbase = in.Pvpresistbase
	// m.Pvpresistcalc = in.Pvpresistcalc
	// m.Pvpresistcap = in.Pvpresistcap
	// m.SpellCategory = in.SpellCategory
	// m.PvpDuration = in.PvpDuration
	// m.PvpDurationCap = in.PvpDurationCap
	// m.PcnpcOnlyFlag = in.PcnpcOnlyFlag
	// m.CastNotStanding = in.CastNotStanding
	// m.CanMgb = in.CanMgb
	// m.Nodispell = in.Nodispell
	// m.NpcCategory = in.NpcCategory
	// m.NpcUsefulness = in.NpcUsefulness
	// m.Minresist = in.Minresist
	// m.Maxresist = in.Maxresist
	// m.ViralTargets = in.ViralTargets
	// m.ViralTimer = in.ViralTimer
	// m.Nimbuseffect = in.Nimbuseffect
	// m.Conestartangle = in.Conestartangle
	// m.Conestopangle = in.Conestopangle
	// m.Sneaking = in.Sneaking
	// m.NotExtendable = in.NotExtendable
	// m.Field198 = in.Field198
	// m.Field199 = in.Field199
	// m.Suspendable = in.Suspendable
	// m.ViralRange = in.ViralRange
	// m.Songcap = in.Songcap
	// m.Field203 = in.Field203
	// m.Field204 = in.Field204
	// m.NoBlock = in.NoBlock
	// m.Field206 = in.Field206
	// m.Spellgroup = in.Spellgroup
	// m.Rank = in.Rank
	// m.Field209 = in.Field209
	// m.Field210 = in.Field210
	// m.Castrestriction = in.Castrestriction
	// m.Allowrest = in.Allowrest
	// m.Incombat = in.Incombat
	// m.Outofcombat = in.Outofcombat
	// m.Field215 = in.Field215
	// m.Field216 = in.Field216
	// m.Field217 = in.Field217
	// m.Aemaxtargets = in.Aemaxtargets
	// m.Maxtargets = in.Maxtargets
	// m.Field220 = in.Field220
	// m.Field221 = in.Field221
	// m.Field222 = in.Field222
	// m.Field223 = in.Field223
	// m.Persistdeath = in.Persistdeath
	// m.Field225 = in.Field225
	// m.Field226 = in.Field226
	// m.MinDist = in.MinDist
	// m.MinDistMod = in.MinDistMod
	// m.MaxDist = in.MaxDist
	// m.MaxDistMod = in.MaxDistMod
	// m.MinRange = in.MinRange
	// m.Field232 = in.Field232
	// m.Field233 = in.Field233
	// m.Field234 = in.Field234
	// m.Field235 = in.Field235
	// m.Field236 = in.Field236
}
